### PR TITLE
Fix adding metadata to metadata groups

### LINKED ISSUE #4285: Adding metadata to nested metadata causes NullPointerException
If you click on the plus:

Screenshot

```
java.lang.NullPointerException
    at org.kitodo.production.forms.createprocess.ProcessFieldedMetadata.preserve(ProcessFieldedMetadata.java:519)
    at org.kitodo.production.forms.createprocess.ProcessFieldedMetadata.getMetadata(ProcessFieldedMetadata.java:449)
    at org.kitodo.production.forms.dataeditor.AddDocStrucTypeDialog.prepareSelectAddableMetadataTypesItems(AddDocStrucTypeDialog.java:510)
```

After that, no more processes can be opened in the metadata editor (not even any other), there is only one white page. You have to log out and log back in to continue.

**Goal:** adding metadata is possible.

### LINKED ISSUE #4457: When adding sub-field in Metadata-Editor, existing sub-fields are doubled
My ruleset has some complex keys/fields, that have sub-fields. E.g. personGroup or corporationGroup.

In Metadata-Editor, I can add such a key, e.g. corporationGroup - that is ok, group is added.

Now I want to add sub-fields: 
- First field (e.g. Displayform) is ok. 
- Next field (e.g. IdentifierPPN) can be added, but another field "DisplayForm" is also added

So, an already existing sub-field in metadata-editor gets doubled, when adding a new sub-field.

Update: this does NOT happen, when I first add the sub-fields one-by-one without entering values. 

The doubling only appears, if I am adding a sub-field, input a value, save - and then add the next sub-field.

Screenshot:
md-editor-corporation-field-doubling

### LINKED ISSUE #4464: Meta Data Editor - add keygroup in keygroup (which should not be possible)
Release 3.3 

If you have a structured keygroup in RuleSet (e.g. "person").
And you try to add a sub-key in this keygroup, you also get a choice in this "add-dialog" to add full keygroup (here "person"),
which leads to strange behaviour including destroying other parts of meta.xml !!!
grafik

-> Please check

### PR DESCRIPTION
**Pull request by solth**
Fixes #4464, fixes #4285

Edit: seems #4465 and #4457 aren't fixed after all

### CODE REVIEW

**Review by IkramMaalej — APPROVED** [review]

**Comment by Kathrin-Huber** [comment]
doubleMetadata

**Comment by Kathrin-Huber** [comment]
lostKeys

**Review by matthias-ronge — COMMENTED** [review]
The right metadata appears to be available for selection at first. Adding also works. But I always have to click two times before the pop-up to open (the fundamental problem that we sometimes have in the metadata editor).

Another problem is, but I don't know whether this is related or a completely different problem, I just noticed: Whenever I click the delete metadata button, I first have to click away a Firefox warning whether I want to leave the page (no) and then again, then it usually works (but not always, and one time I got a warning for a validation error). But it can also be that this is a completely independent problem or it is due to my ruleset, maybe, I can't say that. I haven't been using the button for a long while.

**Comment by solth** [comment]
> The right metadata appears to be available for selection at first. Adding also works. But I always have to click two times before the pop-up to open (the fundamental problem that we sometimes have in the metadata editor).

Yes, this has to do with the update being triggered by the javascript `blur` events (documented in #3821)

> Another problem is, but I don't know whether this is related or a completely different problem, I just noticed: Whenever I click the delete metadata button, I first have to click away a Firefox warning whether I want to leave the page (no) and then again, then it usually works (but not always, and one time I got a warning for a validation error). But it can also be that this is a completely independent problem or it is due to my ruleset, maybe, I can't say that. I haven't been using the button for a long while.

That is a different problem and occurs in the master branch, too.

**Comment by solth** [comment]
> Issue #4457

I think #4457 is about `MetadataGroup` children being unintentionally duplicated. Your screencast shows `MetadataGroups` directly assigned to a structural element being duplicated on purpose. Looks like a similar problem, but not exactly what was described in the issue, IMO.

**Pull request merged**
