### PR TITLE
Import authority records into meta-data groups

### PR DESCRIPTION
**Pull request by matthias-ronge**
This is part of issue #619

### CODE REVIEW

**Comment by henning-gerhardt** [comment]
two remarks for test class files:
- without license header
- white space at end of line

**Comment by matthias-ronge** [comment]
Here, everything is green. Is there any way to find out which test failed, and with what kind of exception?

Eclipse screenshot

**Comment by henning-gerhardt** [comment]
Running test with ant result is similar to travis:
```
    [junit] Running org.kitodo.production.lugh.ld.LiteralTest
    [junit] Tests run: 34, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.064 sec
```

ant script create a test report (`build/test-reports/TEST-org.kitodo.production.lugh.ld.LiteralTest.xml`) and this contains following error message
```xml
...
  <testcase classname="org.kitodo.production.lugh.ld.LiteralTest" name="testLiteralCannotBeCreatedAsRDFLangString" time="0.004">
    <failure message="Expected exception: java.lang.AssertionError" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: Expected exception: java.lang.AssertionError</failure>
  </testcase>
...
```

**Comment by matthias-ronge** [comment]
I fixed the above one. JUnit must be executed with `-ea` option on the JVM to enable assertions. However, I cannot reproduce the last one. On my system it is:

        [junit] Running org.kitodo.production.lugh.ld.ResultTest
        [junit] Tests run: 31, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0,063 sec
    BUILD SUCCESSFUL

Is there a way to see the error log that Travis generates?

**Comment by henning-gerhardt** [comment]
I don't know how to display this created files. But I found an other way to let tests create some [more output](http://stackoverflow.com/questions/5521311/ant-junit-task-does-not-report-detail): adding a formater line to build.xml inside junit part:

```xml
...
            <classpath refid="test.classpath"/>
            <assertions><enable/></assertions>
            <formatter type="xml" usefile="true"/>
            <formatter type="plain" usefile="false" /> <!-- output to screen -->
            <batchtest todir="${test.report.dir}">
                <fileset dir="${build.classes.test}" includes="**/*Test.class"/>
            </batchtest>
...
```

**Comment by henning-gerhardt** [comment]
Maybe this output line should stay for future failing tests in travis?

If everything is working, you should clean up git history a little bit.

**Pull request closed without merging**
