### PR TITLE
Fix multi view state warning when searching

### LINKED ISSUE #5444: Multiview state warning
**Describe the bug**
In certain usage scenarios the message

```
[warning] Multiview state for viewId: "/pages/searchResult.xhtml" and clientId "searchResultTabView:searchResultForm:searchResultTable" not found
```

appears in the catalina.out of the running Tomcat instance. This message is maybe introduced by #5358.

**Expected behavior**
If this warning message is important then they reason should be found and fixed so this message did not appear anymore.

**Release**
3.4.4-snapshot and 3.5.0-beta-1

### PR DESCRIPTION
**Pull request by thomaslow**
Fixes #5444 

Avoids Primefaces warning by checking whether a multi view state is available before clearing it.

### CODE REVIEW

**Comment by solth** [comment]
Please rebase against master to fix broken Github CI builds!

**Comment by henning-gerhardt** [comment]
I can not review this pull request as I only noticed the messages in the `catalina.out` file and I don't know how to produce this messages.

**Comment by thomaslow** [comment]
The message was triggered when a user visits the search result page (for the first time) after performing a search via the global search input. However, it would only appear once. A second visit (or search) should not have produced the warning message again. A logout/login should allow to trigger the message again.

**Review by henning-gerhardt — COMMENTED** [review]
For the descriped way in https://github.com/kitodo/kitodo-production/pull/5445#issuecomment-1330601327 the warning message did not appear anymore.

**Review by henning-gerhardt — APPROVED** [review]

**Pull request merged**
