### PR TITLE
Import authority records into meta-data groups

### PR DESCRIPTION
**Pull request by matthias-ronge**
This is part of issue #619

### CODE REVIEW

**Comment by matthias-ronge** [comment]
The method Travis fails to find is in line 70 of the corresponding file (`static void write(Node, Map, File, String)`). It compiles and executes fine on my machine, so what is the problem here? Maybe a false positive? Can you compile this branch?

**Comment by henning-gerhardt** [comment]
Some notes a review:

Goobi/src/org/kitodo/production/lugh/AuthorityFileUtil.java
- whole file with tab indent
- some lines with white space at end of line

Goobi/src/org/kitodo/production/lugh/ld/AccessibleObject.java
- whole file with tab indent

Goobi/src/org/kitodo/production/lugh/ld/AmbiguousDataException.java
- whole file with tab indent

Goobi/src/org/kitodo/production/lugh/ld/GraphPath.java
- some lines with tab indent
- some lines with white space at end of line

Goobi/src/org/kitodo/production/lugh/ld/IdentifiableNode.java
- whole file with tab indent
- some lines with white space at end of line

Goobi/src/org/kitodo/production/lugh/ld/LinkedDataException.java
- whole file with tab indent
- some lines with white space at end of line

Goobi/src/org/kitodo/production/lugh/ld/Literal.java
- equals and hashCode methods starts with tab indent

Goobi/src/org/kitodo/production/lugh/ld/NamedNode.java
- methods without javadoc

Goobi/src/org/kitodo/production/lugh/ld/NoDataException.java
- whole file with tab indent

Goobi/src/org/kitodo/production/lugh/ld/Node.java
- equals and hashCode method starts with tab indent
- get method with tab indent
- some methods with a plain line between javadoc and method declaration

Goobi/src/org/kitodo/production/lugh/ld/Result.java
- add, node, nodes methods starts with tab indent
- javadoc of strings methods indent by tab


General: 3.000 new lines without a single line for tests. If it is possible, please add tests for Goobi/src/org/kitodo/production/lugh package as this code does not depend on old code.

**Comment by matthias-ronge** [comment]
What do you want for indent currently, tabs or spaces?

**Comment by henning-gerhardt** [comment]
As your new code is most in space indent I would prefer space indent in this new files. New coding guidelines (not official yet) preferred space indent too.

Btw: I can build your branch on my local development system. Why travis integration reports an error is not clear for me.

**Comment by matthias-ronge** [comment]
Spaces also for test cases?

**Comment by henning-gerhardt** [comment]
Some few white spaces at end of line:
- Goobi/src/org/kitodo/production/lugh/AuthorityFileUtil.java
- Goobi/src/org/kitodo/production/lugh/ld/Namespace.java

Questions to NodeReferences with different Zeutschel urls (Goobi/src/org/kitodo/production/lugh/ld/GraphPath.java): 
- should this urls real usable urls as they don't work
- if they are only placeholder domain entries, why not use kitodo.org ?
 
For new code use space indent too. When new coding guidelines are out then we (or maybe I) should reformat whole project to new guidelines.

**Comment by henning-gerhardt** [comment]
Small tests but better then nothing. Can you please add default license header to tests files too?

**Comment by matthias-ronge** [comment]
Something broke. I cannot push to my branch any more. To be safe, I create a new branch, and will create a new pull request based on it then.

**Pull request closed without merging**
