### PR TITLE
Replace Goobi by Kitodo

### PR DESCRIPTION
**Pull request by stweil**

### CODE REVIEW

**Comment by henning-gerhardt** [comment]
Mhh, something strange is happened: no travis check is trigged by your pull request.

**Comment by matthias-ronge** [comment]
There are no java files modified. Perhaps there is some setting for this?

**Comment by henning-gerhardt** [comment]
Travis check should be run on any pull request not only on pull requests with changed java files. Maybe I can look into this this week, if not this must wait after my vacation.

**Comment by stweil** [comment]
Travis now successfully finished.

**Comment by henning-gerhardt** [comment]
Looks ok now. Maybe Travis integration was interrupted.

**Pull request merged**
