### PR TITLE
Execute tests in random order

### PR DESCRIPTION
**Pull request by henning-gerhardt**
This pull request change the order of test execution from default "filesystem" to "random". This can improve the quality of tests as they are not executed in a system specific ordering and bad written tests will be visible.

### CODE REVIEW

**Comment by henning-gerhardt** [comment]
Any comments on this change @kitodo/kitodo-production-developers ?

**Comment by matthias-ronge** [comment]
The Travis tests fail. Please fix that. 😉

**Comment by matthias-ronge** [comment]
I reject nondeterministic tests because they cause errors that only occur occasionally, are not easily reproducible, and therefore cannot be easily fixed. The purpose of the tests is to find errors in branches. If the branch is correct but the test (sometimes) fails, this is not effective.

I also believe—I’m not sure, but I think—that the Selenium tests build on one another, i.e. that elements are added in the AddingST that are deleted in the DeletingST.

**Comment by henning-gerhardt** [comment]
> The Travis tests fail. Please fix that.

That is the reason why I change the run order of the tests because they are failing on my systems (two at least) since weeks but pass on Travis or other systems.

> I reject nondeterministic tests because they cause errors that only occur occasionally, are not easily reproducible, and therefore cannot be easily fixed. The purpose of the tests is to find errors in branches. If the branch is correct but the test (sometimes) fails, this is not effective.

Tests should be written and executed independent of other tests. They should not relay on other previous or later executed tests. Even their execution order should not determinate their pass or failing.

> I also believe—I’m not sure, but I think—that the Selenium tests build on one another, i.e. that elements are added in the AddingST that are deleted in the DeletingST.

I don't hope that this is true and they are (hopefully) independent.

**Comment by matthias-ronge** [comment]
You are welcome to do that, fix all tests and if the tests have run 1000 times without errors, we can gladly take over. At the moment we have [completely different problems](https://github.com/kitodo/kitodo-production/issues?q=is%3Aopen+is%3Aissue+label%3A3.x+-label%3Adocumentation+-label%3Aduplicate+-label%3Afeature+sort%3Acomments-desc).

**Comment by henning-gerhardt** [comment]
Closing as I have no time to fix all "bad written tests" nor there is no general agreement to run tests in random order.

**Pull request closed without merging**
