### PR TITLE
Enumerate logical divisions

### LINKED ISSUE #3826: Sub-Structure in exported METS has "strange" ORDER-Attribute
I have created a simple rule set with two levels of logical structure (monograph/chapter).
When this is exported the chapters have a "strange" ORDER-Attribute in structMap"LOGICAL".
"Strange" means, that the ORDER-Attribute does not follow a simple ordering number, but has instead the ORDER number of the first page, it includes.
Besides this might be very confusing, it could be even formal wrong:
Just imagine 3 chapters beginning on the same page would have the same ORDER, which is wrong from METS point of view.
Please check.

Example:
```
   <mets:structMap TYPE="LOGICAL">
        <mets:div ID="uuid-3bc8e4fd-f4ff-4373-8f45-edea308f8c98" DMDID="uuid-056dab6b-c17c-32ac-b0b7-87a384bea1b0" ADMID="uuid-7503ce07-a13e-345c-befc-3111c996eabc" TYPE="Monograph" ORDER="1" LABEL="202007091123Div">
            <mets:div ID="uuid-b48726e8-1f17-43db-9108-5ff0b43239ba" DMDID="uuid-2e789f22-462b-308d-be98-ac3139f94d2d" TYPE="Chapter" ORDER="1"/>
            <mets:div ID="uuid-33241660-8b31-4174-a593-d1abeead68b9" DMDID="uuid-2c2086c5-d938-3427-8bbe-c14b8cdb00e6" TYPE="Chapter" ORDER="2"/>
            <mets:div ID="uuid-e91798f5-c606-49ce-ac8d-885b48c10711" DMDID="uuid-14eb30c3-c891-328b-bb75-f3854dd8f8ff" TYPE="Chapter" ORDER="6"/>

```
Rule set extract:
```
   <correlation>
        <restriction division="Monograph" unspecified="forbidden">
            <permit division="Chapter"/>

```

### PR DESCRIPTION
**Pull request by matthias-ronge**
Fixes #3826

### CODE REVIEW

**Comment by Kathrin-Huber** [comment]
please rebase

**Comment by stefanCCS** [comment]
Hi,
I have tested this with a version special build on Sep, 29th.
Unfortunately, the results are still not as expected (as described here: [Issue 3826](https://github.com/kitodo/kitodo-production/issues/3826).
It looks like, that still the linked page number is used plus a logic for increasing numbers.
--> Please check.
(I can provide further details e.g. via Skype).

Data extract:
```
                <mets:div ID="DIVL40" DMDID="uuid-c980c4a1-1bc3-32ab-bb64-3ee9cdde4da6" TYPE="CHAPTER" CONTENTIDS="" ORDER="38" LABEL="Chapter4">
                    <mets:div ID="DIVL41" ADMID="uuid-16b7717a-f1ad-373c-ac88-038baaebcaf6" TYPE="TITLE" CONTENTIDS="" ORDER="38"/>
                    <mets:div ID="DIVL42" ADMID="uuid-d5d90437-4d1e-395e-98bf-bb7130dc893b" TYPE="AUTHOR" CONTENTIDS="" ORDER="39"/>
                    <mets:div ID="DIVL43" TYPE="BODY" CONTENTIDS="" ORDER="40">
                        <mets:div ID="DIVL44" TYPE="PARAGRAPH" CONTENTIDS="" ORDER="40">
                            <mets:div ID="DIVL45" ADMID="uuid-3d47b790-60d6-3055-9d7f-3b0962c03a8b" TYPE="TEXT" CONTENTIDS="" ORDER="40"/>
                        </mets:div>
                        <mets:div ID="DIVL46" TYPE="PARAGRAPH" CONTENTIDS="" ORDER="42">
                            <mets:div ID="DIVL47" ADMID="uuid-32f640c7-8111-357c-8247-52ec2158df5c" TYPE="TEXT" CONTENTIDS="" ORDER="42"/>
                        </mets:div>
                        <mets:div ID="DIVL48" TYPE="PARAGRAPH" CONTENTIDS="" ORDER="44">
                            <mets:div ID="DIVL49" ADMID="uuid-0e439edf-5154-35cc-898a-cf8e87e92a9c" TYPE="TEXT" CONTENTIDS="" ORDER="44"/>
                        </mets:div>
                        <mets:div ID="DIVL50" TYPE="PARAGRAPH" CONTENTIDS="" ORDER="46">
                            <mets:div ID="DIVL51" ADMID="uuid-4ce7f927-510a-3bfe-9696-105d0890f29b" TYPE="TEXT" CONTENTIDS="" ORDER="46"/>
                        </mets:div>
                        <mets:div ID="DIVL52" TYPE="PARAGRAPH" CONTENTIDS="" ORDER="48">
                            <mets:div ID="DIVL53" ADMID="uuid-a55337c5-8773-3917-ac99-9fb7623fbcb0" TYPE="TEXT" CONTENTIDS="" ORDER="48"/>
                        </mets:div>
                        <mets:div ID="DIVL54" TYPE="NOTE" CONTENTIDS="" ORDER="50">
                            <mets:div ID="DIVL55" ADMID="uuid-54af7652-a2f7-32ae-b416-b554547378cd" TYPE="TEXT" CONTENTIDS="" ORDER="50"/>
                        </mets:div>
                        <mets:div ID="DIVL56" DMDID="uuid-52783dd9-18ec-3ea7-abc7-287516c36507" TYPE="ILLUSTRATION" CONTENTIDS="" ORDER="52" LABEL="reading it for the first time.">
                            <mets:div ID="DIVL57" ADMID="uuid-5417bfb3-bddb-34e8-9f6e-cd2b6b0e058d" TYPE="IMAGE" CONTENTIDS="" ORDER="52"/>
                            <mets:div ID="DIVL58" ADMID="uuid-d2703a83-d87c-325a-8131-84c527332a91" TYPE="CAPTION" CONTENTIDS="" ORDER="53"/>
                        </mets:div>
                        <mets:div ID="DIVL59" DMDID="uuid-578302e8-a173-33ae-8a72-b48ca7b26784" TYPE="TABLE" CONTENTIDS="" ORDER="55" LABEL="Untitled">
                            <mets:div ID="DIVL60" ADMID="uuid-0306a363-71eb-3c52-b422-487c23d38ee9" TYPE="IMAGE" CONTENTIDS="" ORDER="55"/>
                            <mets:div ID="DIVL61" ADMID="uuid-dd89d744-a3c9-3cb9-a953-f7c9201122c3" TYPE="CAPTION" CONTENTIDS="" ORDER="56"/>
                        </mets:div>
                    </mets:div>
                </mets:div>
```

**Comment by matthias-ronge** [comment]
What is this “special build” and does it at all contain the change? This has not yet been merged, so you would basically have to check out this commit, build it and run the test on that build.

**Comment by stefanCCS** [comment]
@Kathrin-Huber  sent me this "special build" which should contain theses changes here.

**Comment by matthias-ronge** [comment]
Is this _exported_ METS file? The numbers are rewritten during export.

**Comment by stefanCCS** [comment]
No, it is in meta.xml.
I have assumed, it should be also in meta.xml, "somehow correct".

**Comment by matthias-ronge** [comment]
Could you check whether the exported file is what you want?

**Comment by stefanCCS** [comment]
I can confirm, in exported file everything is ok :-)

**Comment by stefanCCS** [comment]
I still have the feeling, it would be much better to have it correct also in meta.xml ...
Anyway, let's take this topic as done (for now) ...

**Pull request merged**
