### PR TITLE
Add GPL3 license text

### PR DESCRIPTION
**Pull request by stweil**
The new text is identical to https://www.gnu.org/licenses/gpl.txt.

Signed-off-by: Stefan Weil sw@weilnetz.de

### CODE REVIEW

**Comment by henning-gerhardt** [comment]
Holdings this pull request until non-warranty clause paragraph for GPL3.0 is approved by management and lawyer.

**Comment by stweil** [comment]
I suggest to add this license text to the Kitodo code and close the PR. That does not automatically imply that we use GPL 3 (although we should because of UGH).

**Comment by stweil** [comment]
This PR can be merged now (and the last commit of PR #522 can be removed).

**Comment by henning-gerhardt** [comment]
I'm voting for closing this pull request in favour for pull request #522 as this license file come from an other project, pull request is against a stale branch and adding license files or other license changes should be done by release management.

**Comment by stweil** [comment]
Closing because PR was against branch 1.11.x.

**Pull request closed without merging**
