### PR TITLE
Use the same sort of white space everywhere

### PR DESCRIPTION
**Pull request by matthias-ronge**
Proposed fix for #650 

Uses (up to) 4 spaces instead for each tab character. Diff with URL option **&w=1** whill show _Whitespace-only changes_ everywhere.

**Note:** This pull request only replaces tabs by spaces. This was scripted. It does **not** correct wrong indentation which still might be necessary in the one or other file.

### CODE REVIEW

**Comment by henning-gerhardt** [comment]
I found 3 xsl files with tab characters inside
- `Goobi/config/docket.xsl`
- `Goobi/config/docket_multipage.xsl`
- `Goobi/plugins/opac/ModsPlugin/org/kitodo/production/plugin/CataloguePlugin/ModsPlugin/kalliope2kitodo.xsl`
I think this files should converted too.

In general: should the `css` files converted? What is there the common indent style?

**Comment by matthias-ronge** [comment]
I did only run the script for files with extensions `.xml`, `.html`, `.java`, `.jsp`, and `.properties`. We have binary files in there, why I did not specify ‘all’. `.xsl` and `.css` feels good. I think we should have only-spaces policy for all text files. However, I consider vector images as binary since I generate and edit them with a paint program, not with a text editor.

**Comment by henning-gerhardt** [comment]
I think converting the `.xsl` and `.css` files should be enough. `.svg` and `.js` files should not be converted.

**Comment by matthias-ronge** [comment]
`.js` should also because it is source code as well (Javascript), or why not?

**Comment by henning-gerhardt** [comment]
It would look like that we maintain and / or modifying this files but we using them only (and really old versions of them) as they are.

If there are other opinions I will respect them and then they should converted too.

**Comment by matthias-ronge** [comment]
Fixed `.xsl` and `.css` files. We should inspect what is up with that javascript stuff. I added another issue for that.

**Pull request merged**
