### PR TITLE
Spell 'cannot' in one word

### PR DESCRIPTION
**Pull request by matthias-ronge**
Though both spellings are acceptable, spelling “cannot” in one word is far more common.

### CODE REVIEW

**Comment by henning-gerhardt** [comment]
"can not" or "cannot" - I would personally prefer "can not" as this spelling is more familiar for me.

There are other opinions? 

@stweil : what did you think?

**Comment by matthias-ronge** [comment]
I checked [Oxford dictionary](https://en.oxforddictionaries.com/usage/cannot-or-can-not) before I crafted this pull request, because I wasn’t sure either. [Here is another article](http://www.dailywritingtips.com/cannot-or-can-not/) that draws the same conclusion.

I think it is a good move in regards to an international community to not just use understandable, but also _common_ English.

**Comment by stweil** [comment]
The standard form is _cannot_. As Matthias has written, there are some (rare) exceptions.

**Comment by henning-gerhardt** [comment]
Ok, I see I must update my preferred spelling to "cannot" :)

**Pull request merged**
