### PR TITLE
Switch to GPL version 3 of Kitodo.Production files

### PR DESCRIPTION
**Pull request by henning-gerhardt**
Add GPL version 3 license file and change header of Kitodo.Production files from GPLv2 to GPLv3.

### CODE REVIEW

**Comment by henning-gerhardt** [comment]
This additional lines in license came from a German lawyer on behalf of Kitodo e. V. So I think, this additional lines are OK.

**Comment by stweil** [comment]
Please don't merge this pull request until we have reached a consensus. More tomorrow.

**Comment by stweil** [comment]
> This additional lines in license came from a German lawyer on behalf of Kitodo e. V. So I think, this additional lines are OK.

See https://www.gnu.org/licenses/gpl-faq.html#ModifyGPL for an official statement of the FSF regarding modifications of the GPL.

**Comment by henning-gerhardt** [comment]
But in your link there are exceptions for GPLv3 mentioned and there is a FAQ entry for changes regarding warranty and liability: https://www.gnu.org/licenses/gpl-faq.html#v3InternationalDisclaimers

**Comment by stweil** [comment]
There are parts in this PR which could be applied now because I think that they are not problematic:

* Update the project attribution ("This file is part of the Goobi Application ...") as suggested.
* Remove the links to other websites ("Visit the websites ...").
* Remove the exception ("Linking this library ...").

There is also consensus that the old name and contact address of the e. V. must be updated:

* Update copyright statement (replace name of Verein and contact address).

I suggest to start with those modifications and apply them in individual pull requests. If everybody agrees, I could prepare such pull requests.

**Comment by henning-gerhardt** [comment]
Negative. This changes should be done by Release Management and done by one commit.

**Comment by stweil** [comment]
> But in your link there are exceptions for GPLv3 mentioned and there is a FAQ entry for changes regarding warranty and liability: https://www.gnu.org/licenses/gpl-faq.html#v3InternationalDisclaimers

Yes, you can add exceptions and disclaimers, but not inside the GPL3 text. It's also possible to remove exceptions (as you are doing in your PR).

**Comment by henning-gerhardt** [comment]
I lock this conversation until German lawyer information is released.

**Comment by henning-gerhardt** [comment]
Re-opened commenting on this  pull-request.

Information from German lawyer on behalf of Kitodo e. V.: unmodified license text of GPL3 is OK and can be used. This is even confirmed by general management of Kitodo e. V.

If there is no big mistake (like slipped license texts / headers) this pull request will be merged today.

**Pull request merged**
