### PR TITLE
Adds a way to import processes that only exist as files

### LINKED ISSUE #5734: Add a way to import processes that only exist as files
A Kitodo Script shall give the opportunity to import processes into Production, that have been created in another system. It works as a bulk import. With the Kitodo Script, there is also the possibility, if a process was deleted from Production, it can be restored, if the files can be restored from a backup.

**Requirement:** The processes to be imported must be in a shared directory (`indir`), which Tomcat can read. Each process is in a subdirectory. In the subdirectory, there must be a Kitodo metadata file named _meta.xml_. Further subdirectories in it can contain files of the process. These are also imported.

Information that is only in the database cannot be imported. That is, the import creates a new process from a production template (`template` = process template ID to use).

In addition to the internal format, parent process can refer to child processes with relative path HREF. These will be converted. But the pure internal format is also possible, here the database ID must correspond to the folder name.

**Error handling:** The _meta.xml_ is validated against the ruleset given in the production template. Links are checked, all links contained in a parent must resolve. If the check fails, the process is completely copied to the error directory (`errors`). Tomcat must have write permission to that directory. An additional file is written in that directory, which contains further information about the error. The erroring processes are not imported.

**Example script call:** `action:importProcesses indir:/media/usb/Shelf_288 template:11 errors:/media/usb/Errors`

_This development is funded by the Municipality of The Hague—Construction Office._

### PR DESCRIPTION
**Pull request by matthias-ronge**
Resolves #5734

### CODE REVIEW

**Comment by solth** [comment]
@matthias-ronge please rebase against current master

**Comment by matthias-ronge** [comment]
Hello @solth. Happy New Year! What is the progress of this pull request?

**Comment by solth** [comment]
Happy New Year to you, too, @matthias-ronge. The PR is assigned to @oliver-stoehr for review, but apparantly he hasn't found time to do it, yet. I will ask him to prioritize this, if possible.

**Review by oliver-stoehr — CHANGES_REQUESTED** [review]
Code looks good so far, I only found one minor typo in a function name.

However, I could not test it on my local machine. I deployed this branch and executed the new Kitodo-Script with the new option (I set the input and error directories, the project id and the template id). I can see the long running task in the task manager, but it stays at 0% progress and the log and error directory are empty. 
Did I miss anything to set up before testing?

**Comment by matthias-ronge** [comment]
@solth Can you merge this, or is still something missing?

**Comment by solth** [comment]
> @solth Can you merge this, or is still something missing?

Approval of a reviewer is missing. I don't know if @oliver-stoehr 's question from above was answered.

**Comment by matthias-ronge** [comment]
Thanks for pointing that out, I actually hadn't seen that was a question.

I'll look at this again and clarify.

**Comment by matthias-ronge** [comment]
@oliver-stoehr:
> However, I could not test it on my local machine. I deployed this branch and executed the new Kitodo-Script with the new option (I set the input and error directories, the project id and the template id). I can see the long running task in the task manager, but it stays at 0% progress and the log and error directory are empty. Did I miss anything to set up before testing?

I found the problem and fixed it. Thanks you for pointing it out.

**Comment by matthias-ronge** [comment]
**Will be merged through pull request #5903.**

**Comment by matthias-ronge** [comment]
Reopened to see if this still builds with the changes requested in PR #5903

**Pull request closed without merging**
