### PR TITLE
Fix #549: Remove step search by user

### LINKED ISSUE #549: Deactivate filter option
It is possible to filter processes in Kitodo.Production by users "Schritt abgeschlossen von Benutzer:"

image01

A request on the community mailing list [1] revealed that due to data privacy protection, this function is not needed or even rejected. To prevent manual disabling of the function after installing a new version it is hereby suggested to remove the function completely in Kitodo.Production. 

[1] https://maillist.slub-dresden.de/pipermail/kitodo-community/2016-July/000000.html

### PR DESCRIPTION
**Pull request by henning-gerhardt**
This pull request remove the search for steps assigned by a user this includes done steps but even open or in progress steps.

### CODE REVIEW

**Comment by frank-ulrich-weber** [comment]
Why remove this filter option? It is a problem due to data privacy protection especially in Germany/EU.
In other countries where we install and use Kitodo such kind of filters are required!

Wouldn’t it be the better idea to make such kind of functionalities switchable and disable them by default?

________________________________

Frank-Ulrich Weber
Product Manager Software Solutions


[cid:Z_Logo_RGB_180px_2b974e26-85b9-4005-92dd-9bb8df881ab3.png]<http://www.zeutschel.de> <http://www.zeutschel.de>

[cid:Facebook-34x34_ab94d89a-875f-49f2-81f3-e136c66e4bb5.png]<https://www.facebook.com/pages/Zeutschel-GmbH/193873073980288?fref=ts>


[cid:Twitter-34x34_f9819937-1c34-4eab-b2fc-944fcf2e8938.png]<https://twitter.com/zeutschelgmbh>


[cid:YouTube-34x34_8cf03759-cc15-472e-a763-e628ea59d43b.png]<http://www.youtube.com/user/zeutschelbookscanner>


[cid:google_34x34_daf218c4-f635-49e8-af7a-ed2a74c251ea.png]<https://plus.google.com/110507211572689796815/posts>


Zeutschel GmbH | Heerweg 2 | 72070 Tübingen | Deutschland
p: +49 (7071) 9706-56 | m: | f: +49 (7071) 9706-44
e: Frank-Ulrich.Weber@zeutschel.de<mailto:Frank-Ulrich.Weber@zeutschel.de> | w: http://www.zeutschel.de

[cid:zeta-banner-86x75_fuerWebsite_c5e46c08-490e-49fa-b13f-d59217ddd169.png]<http://www.zeutschel.de/links/Zeta-App>


Geschäftsführer/President: Joerg Vogler | Registergericht Stuttgart: HRB 380917

**Comment by henning-gerhardt** [comment]
Even if you remove this filter option on user interface, you can still use "stepdoneuser:<username>" in filter input field of any search form. If this should be prevented too, there are a lot of changes necessary.

Until Goobi Community CE  1.11.2 this was a hidden and not documented feature.

Is this feature really somewhere used?

**Comment by henning-gerhardt** [comment]
I talked to our in-house data privacy / protection official and he told me to remove this kind of search  from user interface and even the possibility to use such kind of filter through input in user interface.

If somebody want to implement this kind of feature to switch on and off this kind of filter, feel free to open a pull request.

If no such pull request is available before next release (I hope I can make such release end October or mid November) I will merge this pull request, even if this functionality is legal in other countries.

**Comment by stweil** [comment]
Data privacy can already be achieved with the current code by avoiding personal accounts. That's the solution we have chosen for Kitodo (and also for other software). That implies that there is no need to enforce this change with the next release.

**Comment by stweil** [comment]
@henning-gerhardt, even if you remove search features from the user interface that would not be sufficient to satisfy the legal requirements for protection of personal data, as long as such data is still recorded. Either you must store anonymous data or no data at all.

I did not examine the problem in depth, but maybe a solution which is easy to implement could be a configurable software part which makes any user names anonymous before saving them.

What about the list of active users? Even that list might be critical according to European data protection rules if it shows real user names.

**Comment by henning-gerhardt** [comment]
Regarding list of active users and showing which step is closed by which user and date is configurable through `goobi_config.properties` file and there `anonymize` parameter.

Storing personal data is bad (I agree) but if there is no easy way to search for this data then it is acceptable for our data protection official. 

Removing all source code to store personal data should be a goal for future development as this could not be done in a couple of days.

**Comment by stweil** [comment]
@henning-gerhardt, thank you for this really good hint to the `anonymize` parameter. It looks like this is the right way to solve the issue. That parameter already does part of the job, and it should be easy to enhance its usage by disabling additional critical parts from the `jsp` files based on that configuration value. Just look for `!HelperForm.anonymized` in the code to see other examples.

**Comment by henning-gerhardt** [comment]
`anonymize` parameter is for your usage to restrictive as necessary informations got lost. Maybe this boolean parameter must be changed to a multiple value or dived into several parameters.

**Comment by stweil** [comment]
I agree. We are discussing here about options / boolean parameters which allow switching certain program features on or off. Maybe this is a concept for other program features, too (for example to remove complexity from the GUI and show only those features which are needed for a certain installation). Then a general form of such a parameter name could be `withFeaturename`. For the concrete case the parameter could be named `withSearchStepsByUser` (default value false). Programmatically it would be handled similar to  `anonymize`.

**Comment by henning-gerhardt** [comment]
Superseeded by PR #562 .

**Pull request closed without merging**
