### PR TITLE
Moves classes from namespace org.kitodo to org.kitodo.production

### PR DESCRIPTION
**Pull request by matthias-ronge**

### CODE REVIEW

**Comment by matthias-ronge** [comment]
@Beacze do you like to review this?

**Comment by Kathrin-Huber** [comment]
Why are there changes in Config.java?

**Comment by matthias-ronge** [comment]
Because class `PasswordConfig` in module _Kitodo_, which used to be in package `org.kitodo.config`, accesses the methods. After the class has been moved to the `org.kitodo.production.config` package, it can no longer see the `Config` classes’ [package-private](https://mein-javablog.de/access-modifier-package-private/#more-767) methods, so it stops compiling. Therefore, the methods must be declared `protected` in class `Config` so that they are visible to subclasses in other packages. This is basically explained by the concept of package privacy itself.

**Comment by Beacze** [comment]
So maybe instead of changing visibility level you could just maintain package in the way that config classes stay always in the same package? They are closely related to each other.

**Comment by Kathrin-Huber** [comment]
please resolve conflicts (maybe wait till UGH(8) is merged)

**Comment by Kathrin-Huber** [comment]
There are still conflicts

**Comment by matthias-ronge** [comment]
I can not rebasen that: There are over 70 conflicts. It's quicker to do that anew.

**Comment by matthias-ronge** [comment]
I created a new issue for this, #3160

**Pull request closed without merging**
