### PR TITLE
Add selenium test for create process out of template

### PR DESCRIPTION
**Pull request by Beacze**

### CODE REVIEW

**Comment by henning-gerhardt** [comment]
There is at least one merge conflict in

- Kitodo/src/test/java/org/kitodo/selenium/AddingST.java

Please fix / solve this conflict.

**Comment by solth** [comment]
This should probably be merged after #1654 because otherwise the Selenium test will probably fail because of a "There are unsaved changes" warning message that is erroneously displayed at the moment when clicking the 'Save' button.

**Comment by Beacze** [comment]
I have rebased this PR on #1654.

**Comment by henning-gerhardt** [comment]
There is at least one merge conflict in

- Kitodo/src/test/java/org/kitodo/selenium/AddingST.java

Please fix / solve this conflict.

**Pull request merged**
