### PR TITLE
speed up migrationPage

### LINKED ISSUE #4384: Not useable newspaper migration site
If you have a large database with a lot of newspaper processes (over 300,000) and corresponding batches (> 150) using the newspaper migration site is not possible as it takes hours or days  to display this page. While loading this page a lot of SELECT statements - which is ok - but even the same amount of UPDATE statements are started. It is for me unclear why UPDATE statements are used / fired on displaying this page.

Displaying the batches tab on the process page takes one or two minutes and is much faster then displaying the nearly same data on the newspaper migration site.

### PR DESCRIPTION
**Pull request by Kathrin-Huber**
fixes #4384

### CODE REVIEW

**Review by matthias-ronge — COMMENTED** [review]
This makes method `processOwnsYearXML(Process process)` in `FileService` dead code and you could delete it. Alternative suggestion: You combine the two methods  `processOwnsYearXML(Process process)` and  `processOwnsYearXML(Process process, boolean forIndexingAll)` in `FileService` (line 589−603) to this one method:

```java
public boolean processOwnsYearXML(Process process) throws IOException {
    URI yearFile = createYearFile(getMetadataFilePath(process, false, true));
    return fileExist(yearFile);
}
```

That should have the same effect.

**Comment by Kathrin-Huber** [comment]
Thats a pretty good idea! That way I also found that `processOwnsAnchorXML` was dead.

**Review by henning-gerhardt — CHANGES_REQUESTED** [review]
Your changes did not solve the issues mentioned in #4384 as your changes are inside the migration itself and not on displaying the newspaper batches. So you may rename the pull request title and remove the "fixes #4384".

**Comment by henning-gerhardt** [comment]
I must partial revert my last comment as I got confused by the changes which including some refactoring. On a new migrated database the values for `processBaseUri` did not get updated any more and this is a big improvement for migration speed. But this pull request (or at least the current version of it) did not solve the slow page displaying at all as the check for the `year.xml` files are still executed and this takes still a lot of time (even less then storing the changed value in `processBaseUri` to the database and maybe index).

So far as I know the database and its entries there is a `type` field in `batch` table which is holding the information about what kind of batch is stored. Is this not enough to decide the displayed batches on the newspaper migration page?

**Comment by matthias-ronge** [comment]
Slow file system access is a different issue (#3300) which also needs to be taken looked after, but I think this pull request fixes the database updates, and this is what talks are about in #4384

Using the batch.type field should be the best solution to find newspaper batches, I agree to this.

**Pull request merged**
