### PR TITLE
Move local libraries to custom Maven repository

### PR DESCRIPTION
**Pull request by Basti890**
Moved all custom libraries to the Slub-Nexus Maven repository

### CODE REVIEW

**Comment by stweil** [comment]
s/libraies/libraries/ in the subject line.

**Comment by stweil** [comment]
Is it possible to replace all (or at least most) http URLs by https?

**Comment by Basti890** [comment]
The Maven-Central repository supports https. (testet)
Jiha doesn't support https. (testet)
Our Slub-Nexus may support https, but just changing the url doesn't work. There for i asked the colleague who manages the Nexus-Server.

**Comment by Basti890** [comment]
At the moment only maven-central supports https. I added this change to the pull request.

**Comment by stweil** [comment]
Thanks a lot. It would be great to add https to the slub repo as well in the future, but for now it's fine.

**Pull request merged**
