### PR TITLE
Implement Metadata copy button

### PR DESCRIPTION
**Pull request by matthias-ronge**

### CODE REVIEW

**Comment by Kathrin-Huber** [comment]
There are checkstyle Errors.
The Test is failing on my machine :(

**Comment by matthias-ronge** [comment]
> There are checkstyle Errors.

That's right, but not in the files I touched. How does that happen?

> The Test is failing on my machine :(

Then why is it running with me?

Puzzles in the darkness. Questions that require an answer ...

**Comment by henning-gerhardt** [comment]
@matthias-ronge : you should rebase this branch against current master as I fixed a few checkstyle errors in #3073.

**Comment by matthias-ronge** [comment]
I have done. Yes, now the test is broken. Very, very strange ...

**Pull request merged**
