### PR TITLE
Do not render the media view image if no selected gallery media conte…

### LINKED ISSUE #5545: NPE on opening meta data editor without images
**Describe the bug**
Pull request #5467 is introducing a difficult to reproduce issue with processes without images and its derivatives. If you opening  such a process in the meta data editor a null pointer exception is thrown and logged in the Tomcat Localhost log file (not in the catalina.out file like other errors!):

```
15-Feb-2023 11:10:47.112 SEVERE [http-nio-127.0.0.1-8080-exec-7] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [Faces Servlet] in context with path [/kitodo] threw exception
	java.lang.NullPointerException
		at org.primefaces.model.DefaultStreamedContent.getStream(DefaultStreamedContent.java:104)
		at org.primefaces.application.resource.StreamedContentHandler.handle(StreamedContentHandler.java:115)
		at org.primefaces.application.resource.PrimeResourceHandler.handleResourceRequest(PrimeResourceHandler.java:108)
		at javax.faces.application.ResourceHandlerWrapper.handleResourceRequest(ResourceHandlerWrapper.java:72)
		at javax.faces.application.ResourceHandlerWrapper.handleResourceRequest(ResourceHandlerWrapper.java:72)
		at javax.faces.application.ResourceHandlerWrapper.handleResourceRequest(ResourceHandlerWrapper.java:72)
		at javax.faces.application.ResourceHandlerWrapper.handleResourceRequest(ResourceHandlerWrapper.java:72)
		at javax.faces.application.ResourceHandlerWrapper.handleResourceRequest(ResourceHandlerWrapper.java:72)
		at javax.faces.webapp.FacesServlet.service(FacesServlet.java:196)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.kitodo.production.servletfilter.EncodingFilter.doFilter(EncodingFilter.java:68)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.omnifaces.filter.GzipResponseFilter.doFilter(GzipResponseFilter.java:183)
		at org.omnifaces.filter.HttpFilter.doFilter(HttpFilter.java:108)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:337)
		at org.kitodo.production.security.SecurityObjectAccessFilter.doFilter(SecurityObjectAccessFilter.java:89)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
```

Before this pull request #5467 was merged no error nor null pointer exception was thrown on opening a process without any images and derivatives.

The frontend user get no information, that this null pointer exception is happening, but the administrator / log watcher of the system get this null pointer exception at least twice or according to the amount of not existing images / derivatives.

**To Reproduce**
1. Create a new process
2. Open meta data editor for this process from the dash board
3. Look into the Tomcat localhost log file (f.e. /var/log/tomcat/localhost.<current-date>.log) to see this null pointer exception

An other way for reproducing this is to open an already finished process where the images and the derivative files are gone (deleted, archived, ...) in the meta data editor.

**Expected behavior**
Open a process in the meta data editor without any images and derivatives should not throw a null pointer exception in any log file. If such a case is detected by the application a message could be displayed that no images where found and can not be displayed.

**Release**
3.6.0-SNAPSHOT after 2023-02-14

### PR DESCRIPTION
**Pull request by markusweigelt**
…nt is no available

Fixes #5545

### CODE REVIEW

**Comment by henning-gerhardt** [comment]
Not all error cases are fixed yet (2023/02/20).

**Review by henning-gerhardt — APPROVED** [review]
I tested this change with the following use scenarios:

- process without any kind of internal reference (like a new process)
-  migrated 2.x process with only a local reference like every 2.x process
-  process with full references

and in every described scenario 

- without any picture and derivatives files
-  with picture and derivatives files
- with only picture files and without any derivatives files

and the reported null pointer exception did not appear anymore in this combinations. In other possible variants there is still the chance that the reported null pointer exception still occur but then is more wrong as in normal use cases should happen.

Missing tests are bad but not required by the current coding guidelines :-(

**Comment by solth** [comment]
> Missing tests are bad but not required by the current coding guidelines :-(

As a reviewer you are free to request them anyway.

**Comment by henning-gerhardt** [comment]
As there are no tests regarding this issue was available in the past which may cover this issue before it was present I did not request them now.

**Pull request merged**
