### PR TITLE
Documentation for workflow

### PR DESCRIPTION
**Pull request by Beacze**

### CODE REVIEW

**Comment by felixlohmeier** [comment]
pull request #1422 changes the docs structure. I suggest to check and merge #1422 first

**Comment by Beacze** [comment]
Should I close this one for now? Or it can just stay here and I will rebase it on #1422 ?

**Comment by henning-gerhardt** [comment]
If you close this pull request and do a rebase later, then you must open a new pull request. You can leave it open, do a rebase after #1422 is merged and inform me to review it again.

**Comment by Beacze** [comment]
Ok, so it will wait until #1422 is merged.

**Comment by felixlohmeier** [comment]
thx @Beacze !

**Comment by Beacze** [comment]
Rebased

**Pull request merged**
