### PR TITLE
Fix problems with duplicate LDAP logins not being reported

### LINKED ISSUE #4926: Misleading error message on duplicate existence of 'LDAP login's
If there is more than one user record in the database, that have the same value in the 'LDAP login' field (like, a user was deleted and then recreated), the error message is showing: _Login … not found!_ The original error—_Login … was found more than once!_—is hidden, and doesn’t appear to the log file either. The reason is that the error message is thrown as a `UserNotFoundException` and the catching code misleadingly assumed that there were 0 entries, not several, then tries to find the 'LDAP login' on the 'login' field and doesn't find it there.

**Workaround:** Issue database command: `UPDATE user SET ldapLogin = NULL WHERE deleted = 1;`

**Goal:**

- Do not use exceptions as part of the regular control flow
- Search for both 'LDAP login' and 'login' and report duplicates correctly
- When deleting users, set 'LDAP login' to `null`

### PR DESCRIPTION
**Pull request by matthias-ronge**
Fixes #4926

### CODE REVIEW

**Review by henning-gerhardt — CHANGES_REQUESTED** [review]
If I understand your change correct then your change would create an exception if there are unique login information with overlapping ldapLogins like in this example:

Person A (ldapLogin provided by external LDAP service)
- name: Franziska
- surname: Mueller
- login: muellerF
- ldapLogin: mueller

Person B (ldapLogin provided by external LDAP service)
- name: Boris Friedrich
- surname: Mueller
- login: muellerB
- ldapLogin: muellerF

**Comment by matthias-ronge** [comment]
No, the problem occurred when there was a user, which was was “deleted”, but the field _LDAP login_ was not set to `null`, but remained in the database. Later, the same user was recreated, so the value in the field _LDAP login_ existed **twice**.

The problem is: The user enters a “username” and Production tries to figure out whether this is the _LDAP login_, or the _login_. Both is possible.

Assume:

```
id | firstName | lastName | login  | ldapLogin      | deleted
---+-----------+----------+--------+----------------+--------
…
17 | null      | null     | null   | Matthias Ronge | 1
…
42 | Matthias  | Ronge    | mronge | Matthias Ronge | 0
```

Now I try to log in with “Matthias Ronge” and my password. The code should find out whether this is the _LDAP login_ or the _login_.

In this case, the original code found more than one entry and threw a `UsernameNotFoundException("Login " + login + " was found more than once")`, but the `catch` clause saw that there is a `UsernameNotFoundException` and assumed there is **no** database record with that string being the _LDAP login_,  therefore continued with the login using the user’s login name. A login with the value of the field _LDAP login_ didn’t happen, so the user couldn’t log in.

What the code did (simplified):

```java
// String login = "Matthias Ronge";
User user;
try {
    // is String "login" the LDAP login?
    user = UserService.getByLdapLogin(login); // throws UsernameNotFoundException “Login
                                              // Matthias Ronge was found more than once”
} catch (UsernameNotFoundException) { // not found. It is not the LDAP login
    user = UserService.getByLogin(login);
}
```

**Comment by henning-gerhardt** [comment]
But your change did create the conflict which I mentioned above and which is not existing with your change.

**Comment by matthias-ronge** [comment]
Now I understand what you mean. Yes, that’s true, but that's the behaviour from Production v. 2 on already. In your case, Franziska can only log in with the username "mueller", and Boris can log in with the username "muellerF" and "muellerB".

Please understand that this case is rather theoretical. As far as I know, the field _LDAP login_ is not used at all, except to authenticate against Microsoft Active Directory. The `login` is typically always and ever a String without white spaces (at least, I don’t know any other example), where the _LDAP login_ for Microsoft Active Directory must always be in the form of “‹Firstname› ‹Lastname›”, because the query interface of AD doesn’t accept anything else. So, in that case, you would have

Person A (ldapLogin provided by external LDAP service)

- name: Franziska
- surname: Mueller
- login: muellerF
- ldapLogin: Franziska Mueller

Person B (ldapLogin provided by external LDAP service)
 
- name: Boris Friedrich
- surname: Mueller
- login: muellerB
- ldapLogin: Boris Friedrich Mueller

Franziska can then log in to Production with login “muellerf” and “Franziska Mueller”, and Boris can log in with login “muellerb” and “Boris Friedrich Mueller”.

**Comment by matthias-ronge** [comment]
The change re-enables authentication against MS AD in the staging system of one of our customers. So I can confirm it solves the problem described in the issue. I didn’t notice it does break something in another environment where there is no MS AD.

**Pull request merged**
