### PR TITLE
CDI bean management

### PR DESCRIPTION
**Pull request by solth**
Replaces `managed-bean` entries in faces-config.xml with CDI annotations for bean management. This brings several advantages: 

- Managing beans in the corresponding classes themselves via annotations is the recommended way since Java EE 6. This also reduces the XML configuration complexity.
- While JSF can only inject ManagedBeans into other ManagedBeans, CDI can inject any Java object into beans managed with the `Named` annotation. 
- The `ManagedBean` annotation of JSF will be declared deprecated in favour of CDI in JSF 2.3.

### CODE REVIEW

**Comment by henning-gerhardt** [comment]
This PR needs a rebase against current master branch.

**Comment by solth** [comment]
Rebased.

**Comment by henning-gerhardt** [comment]
Two things more:
- With this changes the login form is not cleared after logout. Used user / login name is still displayed.
- On shutdown the application a really big message appears and starts with
```
Jun 16, 2017 12:20:21 PM org.apache.catalina.loader.WebappClassLoaderBase checkThreadLocalMapForLeaks
SEVERE: The web application [/kitodo] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@78f849c5]) and a value of type [org.hibernate.internal.SessionImpl] (value [SessionImpl(PersistenceContext[entityKeys=[EntityKey[org.kitodo.data.database.beans.Project#11], EntityKey[org.kitodo.data.database.beans.Project#12], EntityKey[org.kitodo.data.database.beans.Project#13], EntityKey[org.kitodo.data.database.beans.Project#14], EntityKey[org.kitodo.data.database.beans.Project#15], EntityKey[org.kitodo.data.database.beans.Project#16], EntityKey[org.kitodo.data.database.beans.Project#17], EntityKey[org.kitodo.data.database.beans.Project#18], EntityKey[org.kitodo.data.database.beans.Project#19], EntityKey[org.kitodo.data.database.beans.Project#20], EntityKey[org.kitodo.data.database.beans.Project#21], EntityKey[org.kitodo.data.database.beans.Project#22], EntityKey[org.kitodo.data.database.beans.Project#23], EntityKey[org.kitodo.data.database.beans.Project#24], EntityKey[org.kitodo.data.database.beans.Project#25], EntityKey[org.kitodo.data.database.beans.Project#26], EntityKey[org.kitodo.data.database.beans.Project#27], EntityKey[org.kitodo.data.database.beans.Project#28], EntityKey[org.kitodo.data.database.beans.Project#29], EntityKey[org.kitodo.data.database.beans.Project#30], EntityKey[org.kitodo.data.database.beans.Project#31], EntityKey[org.kitodo.data.database.beans.Project#32], EntityKey[org.kitodo.data.database.beans.Project#33], EntityKey[org.kitodo.data.database.beans.Project#34], EntityKey[org.kitodo.data.database.beans.Project#35],
```
and ends with
```
CollectionKey[org.kitodo.data.database.beans.Property.users#1546864]]];ActionQueue[insertions=org.hibernate.engine.spi.ExecutableList@5d2d2570 updates=org.hibernate.engine.spi.ExecutableList@1e16b24a deletions=org.hibernate.engine.spi.ExecutableList@483d6f3f orphanRemovals=org.hibernate.engine.spi.ExecutableList@6b30e4f7 collectionCreations=org.hibernate.engine.spi.ExecutableList@5f024a44 collectionRemovals=org.hibernate.engine.spi.ExecutableList@742d270c collectionUpdates=org.hibernate.engine.spi.ExecutableList@574aea21 collectionQueuedOps=org.hibernate.engine.spi.ExecutableList@3bb1bb63 unresolvedInsertDependencies=UnresolvedEntityInsertActions[]])]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
```

**Comment by solth** [comment]
> What is the reason behind empty file Kitodo/src/main/resources/META-INF/beans.xml?

`beans.xml` is the CDI deployment descriptor. It can be empty, but is required in order to use CDI with Tomcat (see http://balusc.omnifaces.org/2013/10/how-to-install-cdi-in-tomcat.html). 

Since we need it in the 'Kitodo' module (instead of the 'kitodo-production' root project), which gets packaged in a .jar file, the `beans.xml` file needs to be located in the `META-INF` directory instead of the `WEB-INF` directory (see https://docs.oracle.com/javaee/7/tutorial/cdi-basic013.htm).

**Comment by henning-gerhardt** [comment]
Thank you for this explanation. I'm personally not conviced about a empty zero-byte xml file. I would expect at least a minimal well-formed xml file maybe with a license header and a description (and / or a link) why this file is empty. If somebody found this empty file without any explanation why this file is empty maybe he tried to remove it or search hours for a reason. 

Would it hurt made any difference when this file has some content of comments / explanation?

suggestion:

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--
 *
 * (c) Kitodo. Key to digital objects e. V. <contact@kitodo.org>
 *
 * This file is part of the Kitodo project.
 *
 * It is licensed under GNU General Public License version 3 or later.
 *
 * For the full copyright and license information, please read the
 * GPL3-License.txt file that was distributed with this source code.
 *
-->
<-- 
explanation why this file is empty with maybe link to the site http://balusc.omnifaces.org/2013/10/how-to-install-cdi-in-tomcat.html (weld installation)
-->
```

**Comment by solth** [comment]
> With this changes the login form is not cleared after logout. Used user / login name is still displayed.

Reset the login property in the LoginForm bean - thanks for the hint @henning-gerhardt

**Comment by solth** [comment]
> On shutdown the application a really big message appears and starts with ...

This warning is probably unrelated to the changes made in this PR. I guess the underlying problem exisited before and just became visible due to the inclusion of the `hibernate-validator`.

**Comment by solth** [comment]
> I also get a lot of messages after application close:
> 
> WARNUNG: Cannot serialize session attribute WELD_S#WELD%ManagedBean%STATIC_INSTANCE|/kitodo_/WEB-INF/classes|de.sub.goobi.forms.ProzessverwaltungForm|null|false for session 2F1D1078E79853618F2F966BF91563BF
> java.io.NotSerializableException: org.kitodo.services.ServiceManager
> 
> I get it for almost every form.

These warnings were caused by the ServiceManager instances in the form beans because the ServiceManager class does not implement the `Serializable` interface. I therefore changed the ServiceManager instances to `transient` to skip them during serialization.

**Comment by henning-gerhardt** [comment]
I think this changes as whole looks OK. I will merge this. If there are new problems / issues then they must be resolved separately.

**Pull request merged**
