### PR TITLE
Make a pull request from #4231 [untested]

### LINKED ISSUE #4231: NPE while accessing non-existing CREATEDATE attribute
Following null pointer exception is thrown

```
Exception in thread "Indexing 0 of type PROCESS" java.lang.NullPointerException
        at org.kitodo.dataformat.access.MetsXmlElementAccess.<init>(MetsXmlElementAccess.java:110)
        at org.kitodo.dataformat.access.MetsXmlElementAccess.read(MetsXmlElementAccess.java:194)
        at org.kitodo.production.services.dataformat.MetsService.loadWorkpiece(MetsService.java:102)
        at org.kitodo.production.services.dataformat.MetsService.getBaseType(MetsService.java:81)
        at org.kitodo.production.services.data.ProcessService.getBaseType(ProcessService.java:1643)
        at org.kitodo.production.services.data.ProcessService.addAllObjectsToIndex(ProcessService.java:272)
        at org.kitodo.production.helper.IndexWorker.indexObjects(IndexWorker.java:116)
        at org.kitodo.production.helper.IndexWorker.indexChunks(IndexWorker.java:110)
        at org.kitodo.production.helper.IndexWorker.run(IndexWorker.java:78)
        at java.lang.Thread.run(Thread.java:748)
```

if the meta data file did not contain a `CREATEDATE` attribut in `/mets:mets/mets:metsHdr`.

This was happening after migration 2.x meta data files into the 3.x format on running indexing all data.

The thrown exception was not visible in the frontend nor logged to the Kitodo.Production log. Logging was going to the Tomcat standard log aka catalina.out.

### PR DESCRIPTION
**Pull request by matthias-ronge**
Hopefully fixes #4231

### CODE REVIEW

**Comment by solth** [comment]
I do not have the required Kitodo 2 data, so I cannot review this, sorry.

**Comment by henning-gerhardt** [comment]
Reviewing this changes will need some time as I must recover 2.x data. If this is not possible I can only adjust 2.x data to this specific issue and test your changes.

**Review by henning-gerhardt — CHANGES_REQUESTED** [review]
Your changes did not work and indexing / reading of this file causing this null pointer exception every time.

**Comment by Kathrin-Huber** [comment]
Is fixed by #4451

**Pull request closed without merging**
