### PR TITLE
Synchronize accesses to 'taskList'

### LINKED ISSUE #5771: Task Manager fails with ArrayIndexOutOfBoundsException
**Describe the bug**
In a productive environment with many scripts, sooner or later, Task Manager cannot be opened anymore, showing an error like this:

image_2023_09_06T12_52_33_324Z

Tasks do still run, but cannot be observed anymore. Reloading the page or logging of and logging back on doesn’t fix it, the error is visible to all users. Needs Tomcat restart.

### PR DESCRIPTION
**Pull request by matthias-ronge**
Fixes #5771

### CODE REVIEW

**Comment by henning-gerhardt** [comment]
I can review this pull request after beginning of October 2023.

**Comment by solth** [comment]
@matthias-ronge please rebase against current master.

**Review by henning-gerhardt — CHANGES_REQUESTED** [review]
I'm unsure over your changes and maybe I need more knowledge about thread safe programming to interpret your changes better.

Did I read your changes correct: your changes block parallel access of the thread unsafe list inside the methods after every call get a reference to the list. One access call is manipulating the list and after this the next one (undefined which one) is acting on this list.

My approach was to block the call of the methods itself, manipulate the list and then let the next caller access the changed list independing what the method is doing.

Maybe it is very helpful for understanding this issue is to add tests which shows without your changes that the list can get be broken and your changes fixes this and the list is correct in any case.

**Comment by matthias-ronge** [comment]
I see the main problem as a race condition **between** the `TaskSitter` class **and** the `TaskManager` class. The key point of this pull request is, that all the source code, which accesses the non-thread-safe list, is synchronized on **one** object. Intuitively, I use the task list object itself to synchronize on.

Your approach of simply declaring the methods as `synchronized` would synchronize the methods on TaskSitter on the TaskSitter object (`TaskSitter.this`), **but** the methods of TaskManager on the TaskManager object (`TaskManager.this`). This means that you would have had **two** semaphores, and this can still lead to a race condition.

I can report that this patch is in use as on a customer server, and the problems have not occurred since then.

**Review by henning-gerhardt — COMMENTED** [review]
I can not judge if this changes are correct even with the explanations from @matthias-ronge as my knowledge of parallel programming is to low.

**Comment by sVnsation** [comment]
Changes look good to me. Everytime the `taskList` is accessed by `TaskSitter` or `TaskManager` it's locked to this single thread only with the synchronized keyword. The next thread can only access the `taskList` when the previous thread is finished.

**Comment by matthias-ronge** [comment]
Thanks @sVnsation for the cross-check. @solth, would it be okay to apply the change?

**Pull request merged**
