### PR TITLE
Automatic generation at task completion

### PR DESCRIPTION
**Pull request by matthias-ronge**
Image generation starts automatically when the task is completed.

Note: This branch is stacked on [matthias-ronge/KIT-1010](https://github.com/matthias-ronge/kitodo-production/tree/KIT-1010) and should be merged after pull request #1779.

### CODE REVIEW

**Comment by Kathrin-Huber** [comment]
Where does all the
"Merge remote-tracking branch 'matthias-ronge/KIT-1009' into KIT-1010"
Comments come from? Please use rebase!

**Comment by matthias-ronge** [comment]
Not possible. The branches are stacked onto each other because they depend on each other. So I merge with the prerequisite branch every time I had to change it later. It works, I am doing so since ten years now, really.

Rebase is a great thing if it runs through without conflicts, but if there are conflicts I have to solve the same conflict manually on every commit over and over again. This is too inefficient to practice.

**Comment by Beacze** [comment]
Rebase and conflicts is not a problem. Rebase has very good mechanism to deal with conflicts - much more clear.

**Comment by matthias-ronge** [comment]
No. I have to fix the merge conflict on every commit of rebase again. And how do I handle the branches stacked on top of it? If I rebase an underlying branch, as far as I know, I cannot merge the on-top branch any more. There is weeks of work spent into these branches, I do not want to do anything that I am not sure it will work. I once destroyed a branch, so I am carefuel now. As I said, a rebease is agood thing if it runs through or has minimal conflicts, but when it comes into big conflicts it does not work for me.

**Comment by Beacze** [comment]
GitHub manual: https://help.github.com/articles/resolving-merge-conflicts-after-a-git-rebase/

One command for stacked branches and conflicts in previous branches which are already resolved: git rebase --skip

**Comment by matthias-ronge** [comment]
I will close this pull request because the branch is based on a branch that will be completely redesigned so that the changes will not be able to be backported and this work has to be completely redeveloped.

**Pull request closed without merging**
