### PR TITLE
ConnectionManager: Close database resources on exception (FindBugs)

### PR DESCRIPTION
**Pull request by stweil**
FindBugs warnings:
* Method may fail to close database resource on exception
* Method may fail to clean up stream or resource on checked exception

Fix it by using try-with-resources statements (supported since Java 7).

Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by stweil** [comment]
@henning-gerhardt, maybe it would be good to update the [Coverity scan for Kitodo](https://scan.coverity.com/projects/kitodo-kitodo-production) to get a better overview about the remaining issues.

**Comment by stweil** [comment]
Updated PR because I noticed a word duplication in the debug message, so fix that (unrelated) issue, too.

**Comment by henning-gerhardt** [comment]
@stweil:  If you have more similar changes in development or pending then this changes should be merged first.

**Comment by stweil** [comment]
This one was the last in my current queue. I want to do more work, and a new scan would help.

**Comment by henning-gerhardt** [comment]
Ok, I will initiate a new Coverity run.

**Pull request merged**
