### PR TITLE
Suppress compiler warnings (deprecation)

### PR DESCRIPTION
**Pull request by stweil**
Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by matthias-ronge** [comment]
Deprecations should be a means of documenting that there is something that needs to be fixed. For example, [Prozess.java, l. 573](https://github.com/goobi/goobi-production/blob/master/Goobi/src/de/sub/goobi/beans/Prozess.java#L573) produces the warning
> The method setShowMessages(boolean) from the type LongRunningTask is deprecated.

because `ProcessSwapInTask` is using a deprecated API that could be considered to be fixed along with resolving issue #65. It is however an acceptable decision to add `@SuppressWarnings("deprecation")` to indicate that it is planned to restrain from changing this in the future.

**Comment by henning-gerhardt** [comment]
Why should this suppression done class wide? 

Deprecation warnings should be raised and hint the developer to remove old and / or deprecated API (methods and / or classes). Hiding this won't fix this automatically.

**Comment by stweil** [comment]
I'd consider two different cases:

(1) Using a deprecated method from some external source. This should be fixed as soon as possible by replacing the method because the method won't be supported by future versions.

(2) Using a deprecated method from our own code. Then it is up to us when we will remove the method and fix the calling code.

As long as we don't decide to fix deprecated method calls, we can as well remove the compiler warning. The code which calls deprecated methods can still be found by a simply search for "deprecated".

Of course we should strive to get code with neither "deprecated" suppressions nor with such warnings.

**Comment by henning-gerhardt** [comment]
Your cases are good but I did not see why hiding this messages could help. Searching for hidden messages are a wrong way imho: except persons who wrote this hiddings nobody know how to find them. 

There are so many hidden messages (undocumented configuration parameters for example) or features (mass import from an excel file, module manager, ocr url service, ...) so adding more such stuff would not help anybody.

A better way is 1) open an issue, 2) fix or repair such things, 3) close issue.

**Comment by stweil** [comment]
Currently deprecation warnings are not explicitly enabled. The Java compiler only reports a summary like this:

    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.

I enabled those warning in my local build and would like to enable them by default.

**Comment by matthias-ronge** [comment]
If the code uses a deprecated internal class it is highlighted accordingly so you want to fix it. At least Eclipse does:

high_light

If you put `@SuppressWarnings("deprecation")` for the class the highlighting is removed and the code looks okay. That is why I would vote against this.

**Comment by henning-gerhardt** [comment]
Enabling this deprecation messages would be ok (maybe confusing for someone) but as @matthias-ronge  mentioned add suppress warning annotations on class level should be avoided or not done.

**Comment by stweil** [comment]
I close this PR because there is no consensus to suppress deprecation warnings in the code.
There is consensus that compiler warnings should be fixed. Therefore such warnings should be addressed as an open issue (I'll create one).

**Pull request closed without merging**
