### PR TITLE
Exclude empty packages from build (fix javac warnings)

### PR DESCRIPTION
**Pull request by stweil**
javac reports that it is creating empty classes. Remove them.

Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by stweil** [comment]
@matthias-ronge, perhaps you can review this PR.

**Comment by matthias-ronge** [comment]
The files called `package-info.java` [are there to document packages](http://docs.oracle.com/javase/specs/jls/se7/html/jls-7.html#jls-7.4.1-310). They are recognized by javadoc processors:

mro_0001

The naming as `*.java` files is a bit odd. These files should not contain any code and they do not need to be compiled. Correct solution for this should be to exclude any `package-info.java` files in the build script.

**Comment by matthias-ronge** [comment]
I do not use Ant to build Kitodo Production, so I cannot test it, but [here is the syntax how to exclude files from the `javac` task in ant](https://ant.apache.org/manual/Tasks/javac.html#srcdirnote).

**Comment by henning-gerhardt** [comment]
As this two files provides some documentation they should not be removed. They should be excluded from building.

**Comment by stweil** [comment]
I updated the PR. Now the files are not removed, but excluded.

**Pull request merged**
