### PR TITLE
Import authority records into meta-data groups

### PR DESCRIPTION
**Pull request by matthias-ronge**
This is part of issue #619

### CODE REVIEW

**Comment by henning-gerhardt** [comment]
I'm missing license headers in
- Goobi/src/org/kitodo/production/lugh/Mods.java 
- Goobi/src/org/kitodo/production/lugh/Mets.java

**Comment by henning-gerhardt** [comment]
A question that I rediscovered from your previous  pull requests:

There a different used `NodeReferences` which points to URI's like `http://names.zeutschel.de/GraphPath`. Using this URI's results into dns errors as domain `names.zeutschel.de` does not exists. If this URI's should / could not really usable then we could / should switch the URI's to `http://names.kitodo.org/GraphPath`.

If there any other usage scenario of this URI's then please explain this scenario.

**Comment by matthias-ronge** [comment]
The primary use of URIs in linked data is the same as packages in Java: To prevent accidental duplicate definitions of a name with different semantics—and to define equality of semantics in case that the same URI is reused. At the moment, these URIs are neither imported from elsewhere, nor make it into the METS/MODS documents, so there is no need to publish their definitions. However, if this would ever change in the future it would make sense to set up a domain accordingly and publish them in a machine-readable format. This is what you should have in mind.

`http://names.kitodo.org/̀  seems a good domain to go for. Often, the namespace subdomain is just called `http://ns.whatever.example/` but me, personally, I don’t like that because of the connotation of that two-letter abbreviation in context of German history.

**Comment by henning-gerhardt** [comment]
Thank you for this explanation and changed URI's.

**Pull request merged**
