### PR TITLE
Remove type property from Batch bean

### PR DESCRIPTION
**Pull request by Beacze**
@matthias-ronge please review this changes.

### CODE REVIEW

**Comment by Kathrin-Huber** [comment]
Do we need the value of the type column for migration purposes?
What was the original use for it?

**Comment by matthias-ronge** [comment]
Yes, we need the value for the migration. The value expresses what the batch describes. For all processes in a series-type batch, an overall parent-series process with links must be generated. For all processes in a batch of the type Newspaper, a total newspaper process and annual processes must be generated.

For the sake of completeness: A batch of the type logistics means that the acceptance or completion of a task of the type batch takes over or completes all the tasks of the same name of all other processes within the batch.

**Comment by Kathrin-Huber** [comment]
So we cannot drop the column, right?

**Comment by Beacze** [comment]
Should the migration for removing column be removed?

**Comment by matthias-ronge** [comment]
That depends on how it will work during migration. Well, I would leave it in there. When migrating, care must be taken to ensure that the migration program that will do so will have to run before the database update.

**Comment by Kathrin-Huber** [comment]
If we are not removing it from the database but from the bean, then there will be a hibernate missmatch error, right?

**Comment by Beacze** [comment]
Actuall not ;) Missmatch appears when column is missing, when you have additional there is no problem.

**Comment by Kathrin-Huber** [comment]
Ok, so I'm voting for removing the migration :)

**Pull request merged**
