### PR TITLE
Remove switch to create unreachable production templates

### LINKED ISSUE #3311: Remove switch to create unreachable production templates
The dialog for creating production templates contains a switch named "active". If you set this "off", the production template is not displayed in the list of production templates after creation. It can no longer be reached and can no longer be viewed or edited. (Still, it is possible to create processes from this production template!)

**Goal:** Eliminate switch and functionality. Existing production templates should always be accessible somehow.

### PR DESCRIPTION
**Pull request by matthias-ronge**
Fixes #3311

### CODE REVIEW

**Comment by Kathrin-Huber** [comment]
What about the `active` attribute from the template? Can this be removed too?

**Comment by matthias-ronge** [comment]
It may be intended to put production templates out of use, if they shouldn’t be used any longer?

**Comment by Kathrin-Huber** [comment]
But how can I do that, if the switch is gone? ;-)

**Comment by Kathrin-Huber** [comment]
Please resolve conflicts

**Comment by matthias-ronge** [comment]
It looks like the switch has already gone.

**Comment by solth** [comment]
> It looks like the switch has already gone.

It's still there:
Bildschirmfoto 2022-05-10 um 08 42 01

**Pull request closed without merging**
