### PR TITLE
Transfer necessary configuration step

### PR DESCRIPTION
**Pull request by BFallert**
Drop foreign key in front of drop key.

### CODE REVIEW

**Comment by BFallert** [comment]
Without this step I get only error message when removing the keys

**Comment by henning-gerhardt** [comment]
How did you create your database for Kitodo.Production? 

So far as I know foreign keys are only created if your database is created by hibernate instead of using the SQL files. So standard migration could not recognize this foreign keys as they are created "outside" and with non determinable names.

**Comment by BFallert** [comment]
The Database was created july 2014 when we introduced Goobi. It was done by a external supporter (@frank-ulrich-weber).

**Comment by stweil** [comment]
Maybe we need a more sophisticated upgrade script then if the table names are random, non deterministic?

**Comment by henning-gerhardt** [comment]
Generated names for index or foreign keys are not random generated but depending on used Hibernate version and some other information. It was difficult to get possible values for the index key names but it was not possible for me for the foreign key names as we (and other I asked in this time) did not have a Kitodo.Production database with foreign key relations.

**Pull request merged**
