### PR TITLE
Browser identification

### PR DESCRIPTION
**Pull request by henning-gerhardt**
Split big browser identification statement into smaller one to identify used browser.

### CODE REVIEW

**Comment by stweil** [comment]
Breaking the if statement is not the right solution. The correct solution would be reordering the statements.

**Comment by henning-gerhardt** [comment]
Reordered statements from old "general to specific" to new "specific to general".

**Comment by stweil** [comment]
I suggest to apply PR #506, close PR #505 and create a new PR which replaces `indexOf` and fixes Opera (2 commits).

**Comment by henning-gerhardt** [comment]
Closing this PR as recommend.

**Pull request closed without merging**
