### PR TITLE
Fix #1089: Can not load norm data via https from DNB

### LINKED ISSUE #1089: Can not load norm data via https from DNB
If somebody tries to load person norm data he got a similar error message like in #882.

The resaon behind this is, that now https connections are enforced by a hard redirect. Instead of calling URI http://d-nb.info/gnd/132775026/about/lds.rdf it must now be https://d-nb.info/gnd/132775026/about/lds.rdf

I changed every possible value from http://d-nb.info to https://d-nb.info/ (`authority.default` and `namespace.gnd` in `goobi_config.properties`) but the used proxy mechanism tries to load it with normal http:

```
DEBUG 2017-11-01 13:16:00,958 net.sf.j2ep.ProxyFilter.doFilter(ProxyFilter.java:95)
        Connecting to http://d-nb.info/gnd/132775026/about/lds.rdf
```

### PR DESCRIPTION
**Pull request by henning-gerhardt**
This should fix the nessary need to access site d-nb.info with https through our local proxy construct.

To archive this, I found the project site for library [j2ep on sourceforge.net](https://sourceforge.net/projects/j2ep/) and there is a not merged [feature request to support any scheme on target site](https://sourceforge.net/p/j2ep/feature-requests/4/). 

On GitHub is a fork for this [library available](https://github.com/tfr42/j2ep) which I used as a base for applying the [scheme patch](https://github.com/kitodo/j2ep/tree/scheme_patch), opened a pull request  and build from there the new version of the j2ep library.

I hope this is a good / correct way to do such things.

### CODE REVIEW

**Comment by stweil** [comment]
https://github.com/stweil/j2ep was created from the [SVN repository](https://svn.code.sf.net/p/j2ep/code) using the GitHub importer.

**Comment by sebastian-meyer** [comment]
@stweil Thanks for providing a copy with full history! Unfortunately your copy now is a few commits behind https://github.com/tfr42/j2ep which this fork is based on. Could you please update your branch with the changes from the latter?
Then we can fork your repository and apply the patch to that.

**Comment by stweil** [comment]
Sure, I already considered doing that. Just wanted to give you a chance to look at the other fork [jacarrichan/j2ep](https://github.com/jacarrichan/j2ep).

**Comment by stweil** [comment]
@sebastian-meyer, https://github.com/tfr42/j2ep uses a different directory structure, so the changes cannot be simply merged. As far as I see, they included some cleanup for GitHub / git instead of SourceForge / subversion which is not code relevant, and they addressed logging. Do we really need that part? Wouldn't it be better to just add the scheme patch on top of the original code, optionally do some cleanup for GitHub?

**Comment by sebastian-meyer** [comment]
That's a question for @henning-gerhardt

**Comment by henning-gerhardt** [comment]
The fork at [jacarrichan/j2ep](https://github.com/jacarrichan/j2ep) did not work for me. I unable to use Maven or ant to build a jar file of this library and I must use [tfr42/j2ep](https://github.com/tfr42/j2ep) to apply the patch from sourceforge.net without modification or reimplementing the needed changes.

**Comment by henning-gerhardt** [comment]
@stweil : I tried your fork and I could apply the patch without any modifications. The created jar file is equal (checksum file comparing) to the own of the Kitodo fork. Should we use your fork as a base for this patch?

**Comment by stweil** [comment]
Yes, feel free to do so. We can add a `README.md` and do other cleanup later through pull requests.

**Comment by henning-gerhardt** [comment]
Ok. I closed the pull request on [tfr4/j2ep](https://github.com/tfr42/j2ep) repo, deleted the branch, changed the Kitodo fork from [tfr42/j2ep](https://github.com/tfr42/j2ep) to [stweil/j2ep](https://github.com/stweil/j2ep), applied the schema patch to the new fork and created a [pull request](https://github.com/stweil/j2ep/pull/1) against new origin repo. As created jar files are identical, it was not necessary to update this pull request.

**Pull request merged**
