### PR TITLE
Fix search form

### PR DESCRIPTION
**Pull request by Kathrin-Huber**
This fixes the Problm in the search form and prepares for the usage with index.

### CODE REVIEW

**Comment by Beacze** [comment]
I don't know if I would go so deep with changes if it is only temporal approach before index is used for querying this values.

**Comment by henning-gerhardt** [comment]
I could understood but I tried it with migrated data from our productive system (3.4 mio entries in property table) and after 10 minutes of waiting for displaying this form I stopped the approach. 

With this change this site / form will be usable for every one who has some data inside his database.

Without this change the form is displaying wrong data after a few seconds (3 or 4 on first run).

**Comment by Kathrin-Huber** [comment]
@henning-gerhardt please test, if the search faster now

**Comment by henning-gerhardt** [comment]
It is faster now except for step titles. Querying this values takes a long time.

General note: titles was sorted before and are now unsorted.

**Comment by Kathrin-Huber** [comment]
@henning-gerhardt you can test it again.
I've added the ordering, and it actually IS ordering, but the translation comes after that, so it seems to be unorderd. We will fix that, when we use the index.

**Pull request merged**
