### PR TITLE
#4838 add development profile to kitodo which puts the jsf project st…

### LINKED ISSUE #4838: ViewExpiredException when rendering error.xhtml
I encounter ViewExpiredException when opening a process in the metadata editor. Stack trace is:

```
java.lang.NullPointerException
	at org.kitodo.data.database.beans.User.<init>(User.java:122)
	at org.kitodo.production.services.data.UserService.getCurrentUser(UserService.java:225)
	at org.kitodo.production.controller.SessionClientController.getAvailableClientsOfCurrentUser(SessionClientController.java:148)
	at org.kitodo.production.controller.SessionClientController.userHasOnlyOneClient(SessionClientController.java:61)
	at org.kitodo.production.controller.SessionClientController.getCurrentSessionClientName(SessionClientController.java:47)
	at jdk.internal.reflect.GeneratedMethodAccessor509.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at javax.el.BeanELResolver.getValue(BeanELResolver.java:88)
```
I could find out that this happens when resolving the following expression: `#{SessionClientController.currentSessionClientName}` for which I found only one occurrence, in `navigation.xml`, line 109.

In `UserService.getCurrentUser(UserService.java:225)`:

    public User getCurrentUser() {
        return new User(getAuthenticatedUser());
    }

`getAuthenticatedUser()` returns `null` from `SecurityAccess.getCurrentAuthentication(SecurityAccess.java:139)`:

    protected Authentication getCurrentAuthentication() {
        return SecurityContextHolder.getContext().getAuthentication();
    }

because the security context it picks up doesn’t contain an authentication. The field `authentication` inside it is `null` in the debugger, which is returned.

This happens when I am logged in, and there are subsequent calls to these functions when the page is built, which correctly return the authenticated user.

### PR DESCRIPTION
**Pull request by markusweigelt**
…age on development

When maven profile development is used the JSF PROJECT_STAGE the project stage is set to "Development".

Maven WAR Plugin is updated too btw.

Fixes #4838

### CODE REVIEW

**Review by henning-gerhardt — APPROVED** [review]
Changes are okay. 

Change of `FACELETS_BUFFER_SIZE` to 5 MB should be okay too but must be maybe changed if this value is to big. Default value is 1024.

**Comment by solth** [comment]
Works like a charm! 👍

**Review by matthias-ronge — COMMENTED** [review]
I have to abstain here. I don’t know how Eclipse internally handles the debug mode. So I cannot say, if I test this, if the changes have any effect under Eclipse. I’m sorry.

**Comment by markusweigelt** [comment]
@matthias-ronge Behaviour of this improvement is independent from your IDE.  Maven uses the "Development" Profile by default. For example when you run "mvn clean install" then the web.xml is adjusted during generation and the project stage is set to "Development". This causes the error messages from Java Server Faces to be displayed.

**Pull request merged**
