### PR TITLE
Remove support for Travis use

### PR DESCRIPTION
**Pull request by henning-gerhardt**
CI based on Travis is not anymore the use case, so remove the needed and used code for this usage.

### CODE REVIEW

**Review by solth — COMMENTED** [review]
Do you think it would be possible to adapt the implementation of `MailSender` to reuse it for Github CI instead of Travis instead of removing it? The files in question does seem to contain very little Travis specific code, so perhaps it would be possible to retain this useful functionality?

**Comment by henning-gerhardt** [comment]
This could be possible but I don't know how to archive that. If somebody want to implant this functionality, feel free to re-use this code. I want to only remove unused code.

**Comment by henning-gerhardt** [comment]
I don't know if this functionality was really working or was only working for specific users.

**Comment by solth** [comment]
It only worked partially for me - I did get screenshots send when a selenium test failed, but those sceenshots always only contained an white, empty browser window. So I guess it didn't really work.

**Review by solth — APPROVED** [review]

**Comment by henning-gerhardt** [comment]
Famous last words: we switched from Travis CI to GitHub actions a long time ago and no one was complaining about this missing functionality.

**Pull request merged**
