### PR TITLE
Enable manipulation of child process links in metadata editor

### LINKED ISSUE #3275: Process link cannot be deleted
A process link should be deletable by selecting the structural element which contains it, and then deleting it. This is not possible because the structural element of a link cannot be clicked on.

Cannot click the linked structural element

**Goal:** Allow clicking on linked structural elements again.

### LINKED ISSUE #4738: Enable corrections of volume-processes in the metadata editor
### Problem
In the metadata editor the processes of volumes cannot be identified (only the label of the structure element is shown) and the order of the processes cannot be corrected. 
Theoretically, the order should be correct, when the processes are created correctly. Practically, mistakes will happen and it  should be possible to correct the mistakes. Otherwise, the incorrect process has to be deleted and created again. 

### Solution

<del>1. In the metadata editor the processes of volumes should be labeled with more information about the order. For example according to `use="displaySummary"` for the list in "Title record link" - see #4736. </del>
2022-09-01 (@andre-hohmann): Now, the process titles are shown - see comment below. 

2. In the metadata editor, it should be possible to correct the order processes of volumes manually. 

It is not the goal of this issue to enable the editing of the metadata of the volume processes via the parent process! It is just about the opportunity to <del> identify and </del>  order the volume processes. 

### Example
BändeSortierung01

### PR DESCRIPTION
**Pull request by solth**
Fixes #3275 
Fixes #4738 

Based on #4850 by @matthias-ronge

### CODE REVIEW

**Comment by solth** [comment]
@BartChris thanks for the comments. 

Yes, it is already possible to (re-)establish links to subordinate processes directly from the metadata editor, and in fact it is possible from the very dialog that can be seen in your screenshot. You just have to check the checkbox "Verlinkung" and the GUI of the dialog will change to one that allows you to add process links. This means it is quite easy to create links between parent and child processes, even if a link was accidentally removed. 

Because of this I am not convinved that we need another, separate permission to control whether links between processes can be removed (and added, for that matter), but this is probably something that the users are better suited to decide than me.

Concerning the question of your second edit: that is how Kitodo 3 is designed: only the ruleset controls what structures can be contained in another structure or document. This is of course something which can be discussed, but it something which is currently at the core of Kitodo.Production.

**Comment by BartChris** [comment]
@solth Thanks a lot for your explanation, i forgot about that. While checking that i encountered a bug in the search functionality, for which i made another issue. https://github.com/kitodo/kitodo-production/issues/5509

You are right that the restoration of links to subprocesses is quite easy (if the search function is repaired), but i still am afraid that the deletion of a process link might happen by accident and stays unnoticed. But maybe others have an different oppinion on that. We already had a similar discussion here  

The general feature of adding images to a superordinate process, is probably better discussed in a Github discussion.  https://github.com/kitodo/kitodo-production/pull/5406

**Review by andre-hohmann — APPROVED** [review]
I have tested the following scenario to modify subordinate process titles in the metadata editor view of the superordinate process. 

1 Change the order of subordinate process titles in the metadata editor 
- [The order of the subordinated process titles was changed in the metadata editor. 
- The order of the subordinated process titles was changed in the METS file of the superordinate process.]

2 Unlink subordinate process title in the metadata editor 
- An existing subordinate process title was unklinked in the metadata editor.
- An existing subordinate process title was unklinked in the METS file of the superordinate process. 

3 Add subordinate process title in the metadata editor
- A subordinate process title was added in the metadata editor. 
- A subordinate process title was added in the METS file of the superordinate process. 

The error message described in #5509 could not be reproduced.

Thus, from the user perspective the the PR is approved.

**Comment by solth** [comment]
@andre-hohmann thank you for the review!

> The error message described in #5509 could not be reproduced.

@BartChris already fixed that issue with PR #5514 which has been merged into the master branch. This branch has been rebased against the updated master.

**Review by henning-gerhardt — APPROVED** [review]
Changes look good but the white space changes made is hard to read.

**Pull request merged**
