### PR TITLE
Enable select metadatakey when creating several divisions 

### PR DESCRIPTION
**Pull request by pontus-osterdahl**
Fixes [#5455](https://github.com/kitodo/kitodo-production/issues/5455) by preparing the addable metadata.

### CODE REVIEW

**Comment by IkramMaalej** [comment]
The list of addable metadata  is no longer empty, but the suggested metadata entries are incorrect and do not always match the selected metadata type.

**Comment by IkramMaalej** [comment]
Another small note, it is not possible to add more than one docstruct without adding metadata, there is no 'No selection' entry in the dropdown menu.

**Comment by IkramMaalej** [comment]
The Metadata drop-down list shows the correct suggestions only in the second execution. 
In the first execution, the metadata's suggestions are always coming from the previous 'add element' operation, regardless in which process this operation has been executed.

https://user-images.githubusercontent.com/34158824/211517204-3070194e-e94f-458d-a323-bb263974a88e.mov

**Review by IkramMaalej — COMMENTED** [review]
The Metadata drop-down list shows the correct suggestions only in the second execution.
In the first execution, the metadata's suggestions are always coming from the previous 'add element' operation, regardless in which process this operation has been executed.


https://user-images.githubusercontent.com/34158824/211519828-821fdf25-fc4b-4eae-9b86-d15b2956c08a.mov

**Comment by pontus-osterdahl** [comment]
Many thanks for the comments! The structure type was not reset correctly. Now it should be working.

**Comment by pontus-osterdahl** [comment]
Thanks again! The metadata-selection is now disabled if no docstruct type is selected.

**Review by IkramMaalej — APPROVED** [review]

**Comment by solth** [comment]
@pontus-osterdahl please rebase against current master as your PR is the next merge candidate

**Pull request merged**
