### PR TITLE
Usability MetaDataEditor Image Preview when Zooming

### PR DESCRIPTION
**Pull request by thomaslow**
Related Issues:
- #4661
- #4711 

The proposed pull request fixes the layout issue in the image preview by replacing the corresponding CSS style commands with a flex box layout. The `display: flex` property is [supported by all modern browers](https://caniuse.com/flexbox). 

It also fixes the weird horizontal scrollbar of the thumbnail stripe.

Before:

https://user-images.githubusercontent.com/6214043/167400918-1fa9fd47-87af-4923-a1af-b377780d4440.mp4

After:

https://user-images.githubusercontent.com/6214043/167400933-6b79beee-6e28-4d71-8124-e8373d535a9a.mp4

Tested on Firefox, Chrome (Linux) and Firefox, Chrome, Edge, Opera (Windows).

### CODE REVIEW

**Comment by Kathrin-Huber** [comment]
@matthias-ronge can you confirm, that the layout doesn't slip anymore?

**Comment by matthias-ronge** [comment]
I cannot build it. Error message is: _Ambiguous rule match for /mods/originInfo[1]/dateIssued[1]_
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.kitodo.xmlschemaconverter.XmlSchemaConverterTest
Warning
  XTDE0540: Ambiguous rule match for /mods/originInfo[1]/dateIssued[1]
Matches both
  "element(Q{http://www.loc.gov/mods/v3}originInfo)/element(Q{http://www.loc.gov/mods/v3}dateIssued)[(Q{http://www.w3.org/2001/XMLSchema}string(data(attribute::attribute(Q{}encoding)))) eq "w3cdtf"]" on line 160 of
and "element(Q{http://www.loc.gov/mods/v3}originInfo)[(Q{http://www.w3.org/2001/XMLSchema}string(data(attribute::attribute(Q{}eventType)))) eq "publication"]/element(Q{http://www.loc.gov/mods/v3}dateIssued)" on line 118 of
Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 7.821 sec <<< FAILURE!
shouldConvertMarcToInternalFormat(org.kitodo.xmlschemaconverter.XmlSchemaConverterTest)  Time elapsed: 2.697 sec  <<< ERROR!
java.io.IOException: Server returned HTTP response code: 500 for URL: https://www.loc.gov/search/500/
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1924)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
        at java.base/java.net.URL.openStream(URL.java:1140)
        at org.apache.commons.io.FileUtils.copyURLToFile(FileUtils.java:1068)
        at org.kitodo.xmlschemaconverter.XMLSchemaConverter.downloadXSLTFile(XMLSchemaConverter.java:183)
        at org.kitodo.xmlschemaconverter.XMLSchemaConverter.convert(XMLSchemaConverter.java:108)
        at org.kitodo.xmlschemaconverter.XmlSchemaConverterTest.shouldConvertMarcToInternalFormat(XmlSchemaConverterTest.java:113)
```

If this has been fixed meanwhile, please rebase

**Comment by henning-gerhardt** [comment]
The output from this test

```
Running org.kitodo.xmlschemaconverter.XmlSchemaConverterTest
Warning
  XTDE0540: Ambiguous rule match for /mods/originInfo[1]/dateIssued[1]
Matches both
  "element(Q{http://www.loc.gov/mods/v3}originInfo)/element(Q{http://www.loc.gov/mods/v3}dateIssued)[(Q{http://www.w3.org/2001/XMLSchema}string(data(attribute::attribute(Q{}encoding)))) eq "w3cdtf"]" on line 160 of
and "element(Q{http://www.loc.gov/mods/v3}originInfo)[(Q{http://www.w3.org/2001/XMLSchema}string(data(attribute::attribute(Q{}eventType)))) eq "publication"]/element(Q{http://www.loc.gov/mods/v3}dateIssued)" on line 118 of
```

is existing for a long time already and is not related to the changes.

Why this test is sometimes failing is not clear for me but unrelated to the changes in this pull request

**Comment by matthias-ronge** [comment]
I see, problem is here:

Error 524

**Pull request merged**
