### PR TITLE
Hide trailing comma when folder filegroup is empty

### LINKED ISSUE #5559: Comma at the end of the subfolder path
**Describe the bug**
When adding subfolder without filegroup a comma is displayed at the end of the folder path.

**To Reproduce**
1. Edit project
2. Add subfolder without selecting METS filegroup

**Expected behavior**
No comma should be displayed at the end of subfolder

### PR DESCRIPTION
**Pull request by solth**
Fixes #5559

### CODE REVIEW

**Comment by markusweigelt** [comment]
Unfortunately, I am no longer part of the Kitodo.Production development team, so please enter a different reviewer.

**Comment by BartChris** [comment]
When i add a new folder (with or without filegroup) and delete it directly afterwards i get an exception:

image

This does not happen in current release (3.7.1)

The deletion is still executed.

**Review by BartChris — APPROVED** [review]

**Comment by BartChris** [comment]
The error message does not seem connect to your changes. I approve the PR, which is working as intended.

**Comment by BartChris** [comment]
I added a bug report (not directly related to the behaviour in the PR): https://github.com/kitodo/kitodo-production/issues/6337

**Pull request merged**
