### PR TITLE
Validate task and tasks status in combination

### LINKED ISSUE #3341: Advanced search’s task status filter not working
Selecting a specific task status in the advanced search does not change the search result.

### PR DESCRIPTION
**Pull request by solth**
Fixes #3341 by validating `task` and `taskStatus` in combination, using OmniFaces [validateAllOrNone](https://showcase.omnifaces.org/validators/validateAllOrNone)

Bildschirmfoto 2024-01-12 um 14 20 55

### CODE REVIEW

**Review by markusweigelt — APPROVED** [review]
Works for me! 

Perhaps you could rearrange the sequence of task errors, but it's possible that the behavior is stemming from the Omniface validator.
Therefore, I approve in any case!
image

**Comment by solth** [comment]
> Perhaps you could rearrange the sequence of task errors, but it's possible that the behavior is stemming from the Omniface validator.

I was able to change to order of the validation messages by simple adjusting the corresponding tags!
Bildschirmfoto 2024-01-17 um 11 27 43

**Comment by markusweigelt** [comment]
@solth Ok I was not aware that it could be misunderstood. I meant the sequence of 'Aufgabenstatus, Aufgabe -> Aufgabe, Aufgabenstatus'. Sorry for the insufficient description.

**Comment by solth** [comment]
> @solth Ok I was not aware that it could be misunderstood. I meant the sequence of 'Aufgabenstatus, Aufgabe -> Aufgabe, Aufgabenstatus'. Sorry for the insufficient description.

Do not underestimate my ability to misunderstand people 😄 

But that change was easy, too. Is this how it should look?
Bildschirmfoto 2024-01-17 um 11 53 11

**Comment by markusweigelt** [comment]
😄 Great thx!

**Pull request merged**
