### PR TITLE
Add support of special characters (whitespaces, '#') for filenames

### LINKED ISSUE #5044: Prevent crash if uploaded file contains # character
Image upload in metadata editor crashes, if the filename is i.e. `A-MG_UTTA0#102_OSQ0#62317_12052021_1.tif`.

The stack trace indicates that there is an URL encoding issue:

Snapshot

**Goal:** Either, forbid uploading files with disallowed characters (and show an error message), or handle them. IMHO it would also be okay to replace the `#` with a `_` or that like, if it causes problems.

### PR DESCRIPTION
**Pull request by IkramMaalej**
Fixes #5044

### CODE REVIEW

**Review by henning-gerhardt — COMMENTED** [review]
I'm not reviewing nor testing this changes as
- such file names are not allowed
- we are not using the media upload feature in the meta data editor
- we are not using the Kitodo.Production internal derivatives generator for creating the derivatives

**Review by matthias-ronge — CHANGES_REQUESTED** [review]
Cannot build on Windows. Tests of **Kitodo - File Managment** fail:

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.kitodo.filemanagement.FileManagementTest
[DEBUG] 2023-04-25 09:52:07.482 [main] PropertiesConfiguration - FileName set to kitodo_config.properties
[DEBUG] 2023-04-25 09:52:07.497 [main] ConfigurationUtils - ConfigurationUtils.locate(): base is null, name is kitodo_config.properties
[DEBUG] 2023-04-25 09:52:07.499 [main] DefaultFileSystem - Could not locate file kitodo_config.properties at null: no protocol: kitodo_config.properties
[DEBUG] 2023-04-25 09:52:07.523 [main] ConfigurationUtils - Loading configuration from the context classpath (kitodo_config.properties)
[DEBUG] 2023-04-25 09:52:07.525 [main] PropertiesConfiguration - Base path set to file:///D:/Daten/Eclipse/ws/kitodo-production/Kitodo-FileManagement/target/test-classes/kitodo_config.properties
[DEBUG] 2023-04-25 09:52:07.568 [main] ConfigurationUtils - ConfigurationUtils.locate(): base is null, name is kitodo_config.properties
[DEBUG] 2023-04-25 09:52:07.569 [main] DefaultFileSystem - Could not locate file kitodo_config.properties at null: no protocol: kitodo_config.properties
[DEBUG] 2023-04-25 09:52:07.570 [main] ConfigurationUtils - Loading configuration from the context classpath (kitodo_config.properties)
[DEBUG] 2023-04-25 09:52:07.573 [main] Config - Using configuration from file:/D:/Daten/Eclipse/ws/kitodo-production/Kitodo-FileManagement/target/test-classes/kitodo_config.properties
[INFO ] 2023-04-25 09:52:07.606 [main] KitodoServiceLoader - Loading module jar file from path file:/D:/Daten/Eclipse/ws/kitodo-production/Kitodo-FileManagement/../Kitodo/modules/kitodo-query-url-import-3.6.0-SNAPSHOT-module.jar
[INFO ] 2023-04-25 09:52:07.606 [main] KitodoServiceLoader - Loading module jar file from path file:/D:/Daten/Eclipse/ws/kitodo-production/Kitodo-FileManagement/../Kitodo/modules/kitodo-command-3.6.0-SNAPSHOT-module.jar
[INFO ] 2023-04-25 09:52:08.028 [main] Command - Execution of Command -1695363704 src/test/resources/scripts/script_createDirMeta.bat src\test\resources\testProcess was successful!: [, D:\Daten\Eclipse\ws\kitodo-production\Kitodo-FileManagement>md src\test\resources\testProcess ]
Tests run: 22, Failures: 0, Errors: 3, Skipped: 2, Time elapsed: 3.031 sec <<< FAILURE!
shouldWrite(org.kitodo.filemanagement.FileManagementTest)  Time elapsed: 0.02 sec  <<< ERROR!
java.nio.file.InvalidPathException: Illegal char <:> at index 2: /D:/Daten/Eclipse/ws/kitodo-production/Kitodo-FileManagement/src/test/resources/fileTest/testWrite.txt
        at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
        at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
        at java.base/java.nio.file.Path.of(Path.java:147)
        at java.base/java.nio.file.Paths.get(Paths.java:69)
        at org.kitodo.filemanagement.FileManagement.write(FileManagement.java:83)
        at org.kitodo.filemanagement.FileManagementTest.shouldWrite(FileManagementTest.java:110)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:258)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

shouldRead(org.kitodo.filemanagement.FileManagementTest)  Time elapsed: 0.004 sec  <<< ERROR!
java.nio.file.InvalidPathException: Illegal char <:> at index 2: /D:/Daten/Eclipse/ws/kitodo-production/Kitodo-FileManagement/src/test/resources/fileTest/testRead.txt
        at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
        at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
        at java.base/java.nio.file.Path.of(Path.java:147)
        at java.base/java.nio.file.Paths.get(Paths.java:69)
        at org.kitodo.filemanagement.FileManagement.write(FileManagement.java:83)
        at org.kitodo.filemanagement.FileManagementTest.shouldRead(FileManagementTest.java:94)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:258)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

shouldGetSizeOfDirectory(org.kitodo.filemanagement.FileManagementTest)  Time elapsed: 0.007 sec  <<< ERROR!
java.nio.file.InvalidPathException: Illegal char <:> at index 2: /D:/Daten/Eclipse/ws/kitodo-production/Kitodo-FileManagement/src/test/resources/directorySize/size.txt
        at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
        at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
        at java.base/java.nio.file.Path.of(Path.java:147)
        at java.base/java.nio.file.Paths.get(Paths.java:69)
        at org.kitodo.filemanagement.FileManagement.write(FileManagement.java:83)
        at org.kitodo.filemanagement.FileManagementTest.shouldGetSizeOfDirectory(FileManagementTest.java:249)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:258)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)


Results :

Tests in error:
  shouldWrite(org.kitodo.filemanagement.FileManagementTest): Illegal char <:> at index 2: /D:/Daten/Eclipse/ws/kitodo-production/Kitodo-FileManagement/src/test/resources/fileTest/testWrite.txt
  shouldRead(org.kitodo.filemanagement.FileManagementTest): Illegal char <:> at index 2: /D:/Daten/Eclipse/ws/kitodo-production/Kitodo-FileManagement/src/test/resources/fileTest/testRead.txt
  shouldGetSizeOfDirectory(org.kitodo.filemanagement.FileManagementTest): Illegal char <:> at index 2: /D:/Daten/Eclipse/ws/kitodo-production/Kitodo-FileManagement/src/test/resources/directorySize/size.txt

Tests run: 22, Failures: 0, Errors: 3, Skipped: 2
```

**Review by BartChris — APPROVED** [review]

**Comment by BartChris** [comment]
Works for me, but i only tested the changes on Linux.

**Review by matthias-ronge — APPROVED** [review]
In principle, I can't get the upload to work on Windows for the moment, but my problems don't seem to have anything to do with the pull request. Basically, the Metdata Editor no longer crashes if the filename contains crude characters. In any case an improvement, so thumbs up. The code also looks correct.

**Pull request merged**
