### PR TITLE
Remove `@Tag("isPositive(long)")` statements which cause build warnings

### PR DESCRIPTION
**Pull request by stweil**

### CODE REVIEW

**Comment by stweil** [comment]
See [CI protocol](https://github.com/kitodo/kitodo-production/actions/runs/9812239427/job/27095910148#step:14:1538).

**Comment by stweil** [comment]
The lines were added in pull request #5756.

**Review by henning-gerhardt — CHANGES_REQUESTED** [review]
Instead of removing the useful tag annotation they should be fixed. See [tag usage in JUnit5](https://junit.org/junit5/docs/current/user-guide/#running-tests-tags).

**Comment by stweil** [comment]
I agree, but I don't know how the right fix should look like. Therefore the current commit only removes the ignored tags to avoid warnings.

**Comment by matthias-ronge** [comment]
My mistage. But I didn't know that either: These tags are a problem because they contain parentheses. But in general, we can use these tages.

Found here: https://junit.org/junit5/docs/5.3.0/api/org/junit/jupiter/api/Tag.html

**Review by matthias-ronge — COMMENTED** [review]
Suggested solution: See #6119

**Comment by stweil** [comment]
Superseded by PR #6119.

**Pull request closed without merging**
