### PR TITLE
Implement the METS interface

### PR DESCRIPTION
**Pull request by matthias-ronge**

### CODE REVIEW

**Comment by Kathrin-Huber** [comment]
Again such a big Pull Request!
Changes on the api can be done in a seperate PR. Also the changes in Kitodo-DataFormat and Kitodo core can be split up in two Pull Requests.

Furthermore there are conflicts, that need to be resolved.

**Comment by matthias-ronge** [comment]
Smaller it is not possible, it all depends on everything.
Yes, the changes to the API could have been made in a separate pull request if I had had the time to wait two weeks for it to be merged before I can continue. It just came up in the course of programming that this was still missing, and I needed it the moment so that I could continue.

**Comment by Beacze** [comment]
Smaller is always possible: 

https://github.com/kitodo/kitodo-production/pull/2020
https://github.com/kitodo/kitodo-production/pull/2022
https://github.com/kitodo/kitodo-production/pull/2024
https://github.com/kitodo/kitodo-production/pull/2028

They all were depending on each other.

**Comment by matthias-ronge** [comment]
To easier get an idea of the content of this pull request, see also my drawing on the intranet page “Das neue Production Internformat” under the heading “Interne Objekte”.

**Comment by Kathrin-Huber** [comment]
Please make smaller pull requests. This time it's pretty easy to accomplish.

**Pull request closed without merging**
