### PR TITLE
Rename configuration files

### PR DESCRIPTION
**Pull request by henning-gerhardt**
Renaming configuration files could break a lot of systems (developer, test or productive systems) or pending developments (pull request #641 for example), so I'm unsure if we could or should rename this files.

### CODE REVIEW

**Comment by matthias-ronge** [comment]
Renaming of configuration files should be feature of DFG development, which requires a different setup of the programming environment anyway (Maven…). Git should be able to handle pull requests through file renames.

But I’ve got some other points:

 - All configuration files should be named by one `String` in the class `org.goobi.production.constants.FileNames` and should only be referenced from there (_except_ plugins which should use their own constants, of course). If something breaks it is a good hint to find locations where this is not the case.
 - Why still have the `kitodo_` prefix at all? It is annoying when configuring a system from the shell (just additional typework) and why have both files written with underscores and camel-case? An even better solution would also point out which files have to stay in the `classes/` directory, and which can go to the `KonfigurationVerzeichnis` directory?
 - Perhaps rename `KonfigurationVerzeichnis` and `xsltFolder` to something of the same pattern, and both in English?
- XML files should be named like their root element. Renaming them should include renaming the root element (in most cases, it is not evaluated in the source code anyway).
 - The file `goobi_opac.xml` is read from both the core and the plugin, but both read other parts of it only. It should be split up into two files, each of them containing only the information read in that place.
 - Delete `webapi` config file. We don’t have a plugin using it.
 - Config files from the `WEB-INF/` directory could then move into the config tree as well.
 - By the way, what do `errorfile.jpg` and `iRGB.icc` in the `config/` dir? Wouldn’t they be better in `Kitodo/WEB-INF/classes/` directory [to be created]?

On a throw:

    config
     + classes
     |  + c3p0.properties
     |  + config.properties [goobi_config.properties]
     |  + contentServerConfig.xml
     |  + ehcache.xml
     |  + hibernate.cfg.xml
     |  + log4j.properties
     |  + login_blacklist.txt [goobi_loginBlacklist.txt]
     |  + modules.xml (rename root element, currently `ModuleDesc`)
     |  + quartz.properties
     + config_directory
     |  + collections.xml [goobi_digitalCollections.xml]
     |  + doctypes.xml [goobi_opac.xml] (*)
     |  + projects.xml [goobi_projects.xml]
     |  + properties.xml [goobi_processProperties.xml]
     |  + representations.xml [goobi_metadataDisplayRules.xml]
     + plugins
     |  + opac
     |     + mods_plugin
     |     |  + mods_plugin.xml [kitodo_mods_opac.xml]
     |     + pica_plugin
     |        + diactitics.txt [goobi_opacUmlaut.txt]
     |        + language-codes.txt [goobi_opacLanguages.txt]
     |        + pica_plugin.xml [goobi_opac.xml] (*)
     + WEB-INF
     |  + faces-config.xml
     |  + metadata-editor-config.xml
     |  + reverse-proxy.xml
     |  + web.xml
     + xslt_directory
        + docket_multipage.xml
        + docket.xml

**Comment by henning-gerhardt** [comment]
My goal with this pull request is to end explanations and discussions about this goobi prefix as the product is called Kitodo which I do since a couple of months for new Kitodo users. The DFG based developement has some other approaches to solve this which I could not include into the 2.x branch.

If have no problems with removing this file name prefix. I have no opinion regarding camelCase or some other naming schema of configuration files as I can work with all of them.

Your other improvements and questions should be done separatly from renaming this configuration files. You can open a pull request on each of your suggestions :)

I will answer only to a few:

- `webapi`as long as we has this interface and all buisines logic for this kind of webapi usage, this configuration file should stay as this file is a white list access file

- config files from `WEB-INF` directory: this files are located there as they needed for running the application. We could move them inside source code to an other location but move them on creating the WAR file back to this location. One other thing is that Eclipse (and maybe other IDE's) expecting this files inside `WEB-INF` directory for running on local development systems

- `errorfile.jpg` and `iRGB.icc` files: mechanis inside Kitodo.Contentserver for finding / detecting this files is wrong for the use case inside of an application. Logic look into the whole class path of the application and not into the class path of the jar file. See closed issues #290 and #291.

**Comment by matthias-ronge** [comment]
My gut instinct tells me _not to_ rename the files in the 2.x branch for the reasons you already listed. We also still have the `de.sub.goobi` and `org.goobi` packages here for the same reasons.

**Comment by henning-gerhardt** [comment]
I let this PR open if the community or more people request renamed configuration files.

**Comment by henning-gerhardt** [comment]
Closing as outdated and obsolete.

**Pull request closed without merging**
