### PR TITLE
Add missing variable declarations in JavaScript

### PR DESCRIPTION
**Pull request by stweil**
This fixes several error messages from LGTM:

    Variable decreasingCorner is used like a local variable,
    but is missing a declaration.
    [...]

Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by stweil** [comment]
See https://lgtm.com/projects/g/kitodo/kitodo-production for more information. LGTM can also be added as a CI tool.

**Comment by stweil** [comment]
See also the [results from Codacy CI](https://app.codacy.com/app/UB-Mannheim/kitodo-production/pullRequest?bid=9461559&prid=2448626).

**Comment by henning-gerhardt** [comment]
@stweil : Thank you for reporting and fixing this. If additional tools will be integrated should be decided by @Kathrin-Huber.

**Comment by stweil** [comment]
Please note that [LGTM currently does not check the Java code](https://discuss.lgtm.com/t/java-language-not-detected/1403) (which would make it even more valuable for the project). Maybe this can be clarified and fixed by the SLUB team.

**Pull request merged**
