### PR TITLE
Let getter for password return empty string in UserForm

### LINKED ISSUE #4238: Changing password - previous changed password displayed
If you must change a few user passwords as administrator the previous used password is automatically filled out in the password change dialog!

### PR DESCRIPTION
**Pull request by solth**
Fixes #4238

### CODE REVIEW

**Review by henning-gerhardt — CHANGES_REQUESTED** [review]
If you added a (selenium) test then my review would be more positive, so I must check this change in a manual way and this change may work for the next couple of time. If in the future someone is changing this method and ignoring the method comment than this issue will show up again.

**Comment by matthias-ronge** [comment]
It's always true. An application should consist of 90% testing and 10% implementation. But who pays for it?

**Comment by henning-gerhardt** [comment]
>  An application should consist of 90% testing and 10% implementation. But who pays for it?

You are paying now for less investments in future where the costs of repairing will be much bigger then implementing it now.

**Comment by matthias-ronge** [comment]
I know that myself, I mean who is paying me / us to do this now?

**Comment by solth** [comment]
Generally I agree with the idea of having as much funcitionality covered by tests, but at the same time I think we should apply some common sense when deciding in which cases they are really necessary. 

This particular change just affects a _getter_ called by the GUI - that now just returns a static value, nonetheless - for which the requirement of a dedicated Selenium test seems a bit obsessive, IMHO.

**Pull request merged**
